// ============================================================
//  data.js — RV Parks USA
//  HOW TO ADD A NEW STATE:
//  1. Copy one of the state objects below as a template
//  2. Change the "state" field on every park entry
//  3. Push your changes — the site rebuilds automatically
//
//  REQUIRED FIELDS PER PARK:
//    name, city, county, state, region, type, sites,
//    hookup, phone, web, tags, address
//
//  VALID TYPES: "Private"
//
//  HOOKUP KEYWORDS (used by filter):
//    "Full hookups" | "Electric" | "Water" | "No hookups"
// ============================================================

const PARKS = [

  // ──────────────────────────────────────────────────────────
  //  TENNESSEE  (27 parks)
  // ──────────────────────────────────────────────────────────

  { name:"Mountain Glen RV Park", address:"6182 Brockdell Rd, Greeneville, TN 37745", year:"", city:"Greeneville", county:"Greene", state:"Tennessee", region:"East TN", type:"Private", sites:45, hookup:"Full hookups, 50A, pull-throughs", phone:"(423) 234-0404", web:"mountainglenrv.com", tags:["Fishing pond","Pavilion","WiFi"] },
  { name:"Creekside RV Park", address:"2475 Henderson Springs Rd, Pigeon Forge, TN 37863", year:"", city:"Pigeon Forge", county:"Sevier", state:"Tennessee", region:"East TN", type:"Private", sites:42, hookup:"Full hookups (W/E/S), concrete pads", phone:"(865) 428-4801", web:"creeksidervpark.com", tags:["Little Pigeon River","Smokies"] },
  { name:"Up the Creek RV Camp", address:"1919 Little Valley Rd, Pigeon Forge, TN 37862", year:"", city:"Pigeon Forge", county:"Sevier", state:"Tennessee", region:"East TN", type:"Private", sites:60, hookup:"Full hookups, concrete pads, fire pits", phone:"(865) 453-8474", web:"upthecreekrvcamp.com", tags:["Smokies","Dollywood nearby"] },
  { name:"Mecca Camp Resort", address:"1301 Mecca Pike, Tellico Plains, TN 37385", year:"", city:"Tellico Plains", county:"Monroe", state:"Tennessee", region:"East TN", type:"Private", sites:50, hookup:"Full hookups, 30/50A", phone:"(423) 253-2266", web:"meccacampresort.com", tags:["Cherokee NF","Cherohala Skyway","Family events"] },
  { name:"Rivers Edge Campground", address:"4220 Huskey St, Pigeon Forge, TN 37863", year:"", city:"Pigeon Forge", county:"Sevier", state:"Tennessee", region:"East TN", type:"Private", sites:60, hookup:"Full hookups, riverside sites", phone:"(865) 453-5734", web:"riversedgepigeonforge.com", tags:["Pigeon River","Smokies","Dollywood"] },
  { name:"Camp LeConte Luxury Outdoor Resort", address:"1739 E Pkwy, Gatlinburg, TN 37738", year:"", city:"Gatlinburg", county:"Sevier", state:"Tennessee", region:"East TN", type:"Private", sites:55, hookup:"Full hookups, 30/50A, WiFi", phone:"(865) 436-6716", web:"campinggatlinburg.com", tags:["Gatlinburg","Pool","Hot tub","Smokies"] },
  { name:"Smoky Waters Campground", address:"346 Wears Valley Rd, Townsend, TN 37882", year:"", city:"Townsend", county:"Blount", state:"Tennessee", region:"East TN", type:"Private", sites:45, hookup:"Full hookups, pull-throughs", phone:"(865) 448-6421", web:"", tags:["Little River","Smokies gate","Quiet valley"] },
  { name:"Lakeview RV Resort", address:"4550 Hwy 11 E, Bluff City, TN 37618", year:"", city:"Bluff City", county:"Sullivan", state:"Tennessee", region:"East TN", type:"Private", sites:50, hookup:"Full hookups (W/E/S), WiFi, 30/50A", phone:"(423) 538-7090", web:"lakeviewrvresort.net", tags:["Boone Lake","Tri-Cities area","Year-round"] },
  { name:"Raccoon Mountain Campground", address:"319 W Hills Dr, Chattanooga, TN 37419", year:"", city:"Chattanooga", county:"Hamilton", state:"Tennessee", region:"East TN", type:"Private", sites:70, hookup:"Full hookups, gravel pads, 30/50A", phone:"(423) 821-9403", web:"raccoonmountain.com", tags:["Chattanooga","Caverns","Mountain views"] },
  { name:"Long Creek Haven", address:"1430 TN-340, Del Rio, TN 37727", year:"", city:"Newport", county:"Cocke", state:"Tennessee", region:"East TN", type:"Private", sites:20, hookup:"Full hookups, 30/50A, creek access", phone:"", web:"", tags:["Pigeon River tributary","Small park","Quiet"] },
  { name:"Bucks Ranch", address:"2193 Keazy Hollow Rd, Telford, TN 37690", year:"", city:"Telford", county:"Washington", state:"Tennessee", region:"East TN", type:"Private", sites:25, hookup:"Electric + water", phone:"", web:"", tags:["Rural East TN","Quiet","Small family park"] },
  { name:"Spring Lake RV Resort", address:"255 Fairview Dr, Spring City, TN 37381", year:"", city:"Spring City", county:"Rhea", state:"Tennessee", region:"East TN", type:"Private", sites:64, hookup:"Full hookups, 30/50A, WiFi, cable", phone:"(423) 365-6555", web:"", tags:["Watts Bar Lake","Monthly rates"] },
  { name:"Grand Ole RV Resort & Market", address:"708 N Main St, Goodlettsville, TN 37072", year:"", city:"Goodlettsville", county:"Davidson", state:"Tennessee", region:"Middle TN", type:"Private", sites:75, hookup:"Full hookups (W/E/S), gravel pads", phone:"(615) 851-4555", web:"grandolervresort.com", tags:["Nashville area","Live music","Restaurant"] },
  { name:"Two Rivers Campground", address:"2616 Music Valley Dr, Nashville, TN 37214", year:"", city:"Goodlettsville", county:"Davidson", state:"Tennessee", region:"Middle TN", type:"Private", sites:65, hookup:"Full hookups, WiFi", phone:"(615) 883-8559", web:"tworiverscampground.com", tags:["Nashville","Opryland area","Pool"] },
  { name:"RJourney Clarksville RV Resort", address:"1270 Tylertown Rd, Clarksville, TN 37040", year:"", city:"Clarksville", county:"Montgomery", state:"Tennessee", region:"Middle TN", type:"Private", sites:97, hookup:"Full hookups, pull-throughs, 30/50A", phone:"(931) 774-7901", web:"rjourney.com", tags:["Fort Campbell area","Nashville day trip"] },
  { name:"Piney River Resort", address:"6869 Piney River Rd N, Bon Aqua, TN 37025", year:"", city:"Dickson", county:"Dickson", state:"Tennessee", region:"Middle TN", type:"Private", sites:60, hookup:"Full hookups, concrete pads, riverfront sites", phone:"(931) 996-3431", web:"pineyriverresort.com", tags:["Piney River","Nashville day trip"] },
  { name:"Campers RV Park", address:"Spring Hill, TN 37174", year:"", city:"Spring Hill", county:"Maury", state:"Tennessee", region:"Middle TN", type:"Private", sites:50, hookup:"Full hookups, 30/50A", phone:"(615) 302-5775", web:"", tags:["Short-term & monthly","Nashville area"] },
  { name:"Country Life RV Parks and Services", address:"1204 Campground Rd, Clarkrange, TN 38553", year:"", city:"Clarkrange", county:"Fentress", state:"Tennessee", region:"Middle TN", type:"Private", sites:30, hookup:"Full hookups", phone:"(931) 863-3000", web:"", tags:["Rural","Monthly rates"] },
  { name:"Gracious Gardens RV Park", address:"Crossville, TN 38555", year:"", city:"Crossville", county:"Cumberland", state:"Tennessee", region:"Middle TN", type:"Private", sites:40, hookup:"Full hookups, 30/50A", phone:"(931) 707-7979", web:"", tags:["Cumberland Plateau","Monthly rates"] },
  { name:"Harmony Ridge RV Park", address:"2850 McGee Rd, Jamestown, TN 38556", year:"", city:"Jamestown", county:"Fentress", state:"Tennessee", region:"Middle TN", type:"Private", sites:30, hookup:"Full hookups, 30/50A", phone:"(931) 879-8080", web:"", tags:["Big South Fork area","Rural","Monthly rates"] },
  { name:"Big Puckett's Campground & RV Park", address:"1037 Austin Rd, Cookeville, TN 38583", year:"", city:"Cookeville", county:"Putnam", state:"Tennessee", region:"Middle TN", type:"Private", sites:35, hookup:"Full hookups, 30/50A", phone:"(931) 858-2253", web:"", tags:["Burgess Falls nearby","Caney Fork fishing"] },
  { name:"Tennessee River RV Resort", address:"185 S River Front Dr, Clifton, TN 37716", year:"", city:"Clifton", county:"Wayne", state:"Tennessee", region:"Middle TN", type:"Private", sites:40, hookup:"Full hookups, 30/50A, river access", phone:"", web:"", tags:["Tennessee River","Boat ramp"] },
  { name:"Coyote View RV Park", address:"2029 Phebus Ln, Union City, TN 38261", year:"", city:"Union City", county:"Obion", state:"Tennessee", region:"West TN", type:"Private", sites:30, hookup:"Full hookups, 30/50A", phone:"(731) 599-9898", web:"coyoteview.com", tags:["Reelfoot Lake area","RV repair on-site"] },
  { name:"Eagle's Nest RV Park", address:"100 Eagle Nest Rd, Buchanan, TN 38222", year:"", city:"Buchanan", county:"Henry", state:"Tennessee", region:"West TN", type:"Private", sites:33, hookup:"Full hookups (W/E/S), concrete pads, 30/50A", phone:"(731) 232-0222", web:"eaglesnesttn.com", tags:["Kentucky Lake","Fishing"] },
  { name:"Parker's Ridge RV Park", address:"460 Murphy Rd, Wildersville, TN 38388", year:"", city:"Wildersville", county:"Henderson", state:"Tennessee", region:"West TN", type:"Private", sites:40, hookup:"Full hookups, 30/50A", phone:"(731) 986-4894", web:"", tags:["Rural West TN","Monthly rates"] },
  { name:"Graceland RV Park & Campground", address:"3691 Elvis Presley Blvd, Memphis, TN 38116", year:"", city:"Memphis", county:"Shelby", state:"Tennessee", region:"West TN", type:"Private", sites:65, hookup:"Full hookups (W/E/S), pull-throughs", phone:"(901) 396-7125", web:"graceland.com/rv-park-campground", tags:["Memphis","Elvis Presley Blvd","Year-round"] },
  { name:"Thousand Trails Natchez Trace", address:"1363 Napier Rd, Hohenwald, TN 38462", year:"", city:"Hohenwald", county:"Lewis", state:"Tennessee", region:"West TN", type:"Private", sites:99, hookup:"Full hookups, 30/50A", phone:"(888) 707-1477", web:"thousandtrails.com", tags:["Membership park","Lake","Dog park","Pool"] },

  // ──────────────────────────────────────────────────────────
  //  TENNESSEE — LARGE PARKS, 100+ sites  (4 parks)
  // ──────────────────────────────────────────────────────────

  { name:"Greenbrier Campground", address:"2353 East Pkwy, Gatlinburg, TN 37738", year:"", city:"Gatlinburg", county:"Sevier", state:"Tennessee", region:"East TN", type:"Private", sites:120, hookup:"Full hookups, 20/30/50 amp, cable TV, WiFi", phone:"(865) 430-7415", web:"smokymountaincamping.com", tags:["Little Pigeon River","Near Greenbrier entrance to Smokies","Cabins available","River-frontage sites"] },
  { name:"Pigeon Forge/Gatlinburg KOA Holiday", address:"3122 Veterans Blvd, Pigeon Forge, TN 37863", year:"", city:"Pigeon Forge", county:"Sevier", state:"Tennessee", region:"East TN", type:"Private", sites:187, hookup:"Full hookups, 30/50 amp, cable, WiFi", phone:"(865) 453-7903", web:"koa.com", tags:["Big rig friendly","Pool","Near Dollywood","Cabins & pull-through sites"] },
  { name:"Pigeon Forge Landing RV Resort", address:"455 Lonesome Valley Rd, Sevierville, TN 37862", year:"", city:"Sevierville", county:"Sevier", state:"Tennessee", region:"East TN", type:"Private", sites:237, hookup:"Full hookups, 30/50/100 amp, concrete pads, cable, WiFi", phone:"(865) 446-1500", web:"rvcoutdoors.com", tags:["Little Pigeon River","Big rig friendly","Zip line & pool","Near Dollywood"] },
  { name:"Sun Outdoors Pigeon Forge", address:"1004 Parkway, Sevierville, TN 37862", year:"", city:"Sevierville", county:"Sevier", state:"Tennessee", region:"East TN", type:"Private", sites:297, hookup:"Full hookups, 20/30/50 amp, concrete pads, cable TV, WiFi", phone:"(800) 758-5267", web:"sunoutdoors.com", tags:["Formerly River Plantation RV Resort","On the Little Pigeon River","Lazy river pool","Big rig friendly"] },

  // ──────────────────────────────────────────────────────────
  //  ALABAMA  (8 parks)
  // ──────────────────────────────────────────────────────────

  { name:"Arrowhead RV Resort at Smith Lake", address:"761 County Rd 941, Crane Hill, AL 35053", year:"", city:"Crane Hill", county:"Cullman", state:"Alabama", region:"North AL", type:"Private", sites:60, hookup:"Full hookups, 30/50A, lakeside sites", phone:"(256) 739-6767", web:"arrowheadsmithlake.com", tags:["Lewis Smith Lake","Boat dock","Bar & Grill","Fishing"] },
  { name:"Desoto Caverns Family Campground", address:"5181 DeSoto Caverns Pkwy, Childersburg, AL 35044", year:"", city:"Childersburg", county:"Talladega", state:"Alabama", region:"North AL", type:"Private", sites:50, hookup:"Full hookups, 30A + some 50A", phone:"(256) 378-7252", web:"desotocavernspark.com", tags:["Caverns","Family activities","Talladega NF nearby"] },
  { name:"Noccalula Falls Campground", address:"1890 Noccalula Rd, Gadsden, AL 35901", year:"", city:"Gadsden", county:"Etowah", state:"Alabama", region:"North AL", type:"Private", sites:94, hookup:"Full hookups (W/E/S), pull-throughs, 30/50A", phone:"(256) 549-4663", web:"gadsdenal.gov/noccalula-falls-park", tags:["Waterfall","Pioneer Village","Pool","Miniature train"] },
  { name:"Bama RV Park", address:"5461 Skyland Blvd E, Cottondale, AL 35453", year:"", city:"Tuscaloosa", county:"Tuscaloosa", state:"Alabama", region:"Central AL", type:"Private", sites:60, hookup:"Full hookups (W/E/S), 30/50A", phone:"(205) 556-6063", web:"", tags:["University town","I-20/59 corridor","Monthly rates"] },
  { name:"Bohamia Glamping & RV", address:"2491 Berney Station Rd, Talladega, AL 35160", year:"", city:"Talladega", county:"Talladega", state:"Alabama", region:"Central AL", type:"Private", sites:30, hookup:"Electric + water, 30/50A", phone:"", web:"bohamia.com", tags:["Talladega NF","Glamping","Quiet","NASCAR area"] },
  { name:"Winner's Circle RV Resort", address:"7970 Bellingrath Rd, Theodore, AL 36582", year:"", city:"Theodore", county:"Mobile", state:"Alabama", region:"South AL", type:"Private", sites:99, hookup:"Full hookups (W/E/S), pull-throughs, 30/50A", phone:"(251) 653-9220", web:"", tags:["Mobile area","I-10 corridor","Monthly rates"] },
  { name:"Tropical Island RV Resort", address:"2252 Creek Winds Rd, Foley, AL 36535", year:"", city:"Foley", county:"Baldwin", state:"Alabama", region:"South AL", type:"Private", sites:85, hookup:"Full hookups, 30/50A, WiFi", phone:"(251) 943-3456", web:"", tags:["Gulf Shores area","Pool","15 min to beach"] },
  { name:"Lakeside Landing RV Park", address:"22206 US Hwy 431, Guntersville, AL 35976", year:"", city:"Guntersville", county:"Marshall", state:"Alabama", region:"North AL", type:"Private", sites:45, hookup:"Full hookups (W/E/S), 30/50A, waterfront sites", phone:"(256) 582-2622", web:"", tags:["Guntersville Lake","Fishing","Boat ramp"] },

  // ──────────────────────────────────────────────────────────
  //  ALABAMA — LARGE PARKS, 100+ sites  (5 parks)
  // ──────────────────────────────────────────────────────────

  { name:"Gulf Shores RV Resort", address:"18717 Barefoot Way, Gulf Shores, AL 36542", year:"", city:"Gulf Shores", county:"Baldwin", state:"Alabama", region:"South AL", type:"Private", sites:176, hookup:"Full hookups, 30/50 amp, water, sewer, cable, concrete pads", phone:"(251) 244-1015", web:"rvcoutdoors.com/gulf-shores-rv-resort", tags:["Waterfront lake sites","Heated pool","Pickleball","Stocked fishing lakes"] },
  { name:"Island Retreat RV Park", address:"18201 State Highway 180, Gulf Shores, AL 36542", year:"", city:"Gulf Shores", county:"Baldwin", state:"Alabama", region:"South AL", type:"Private", sites:173, hookup:"Full hookups, 20/30/50 amp, concrete pads", phone:"(251) 967-1666", web:"islandretreatrvpark.com", tags:["Pull-thru & back-in sites","Pool","Clubhouse","RVs only, 15-years-or-newer rule"] },
  { name:"Bay Palms RV Resort", address:"15440 Dauphin Island Pkwy, Coden, AL 36523", year:"", city:"Coden", county:"Mobile", state:"Alabama", region:"South AL", type:"Private", sites:170, hookup:"Full hookups, 30/50 amp, sewer, paved sites", phone:"(251) 873-4700", web:"baypalmsrvresort.com", tags:["Big rig friendly (up to 70 ft)","Pool","Dog park","RV-only resort"] },
  { name:"Sun Outdoors Orange Beach", address:"22800 Canal Rd, Orange Beach, AL 36561", year:"", city:"Orange Beach", county:"Baldwin", state:"Alabama", region:"South AL", type:"Private", sites:142, hookup:"Full hookups, some pull-thru sites", phone:"(844) 707-4343", web:"sunoutdoors.com/alabama/sun-outdoors-orange-beach", tags:["Pull-thru sites","Resort amenities","Year-round"] },
  { name:"Two Lakes RV Resort", address:"22353 Twin Lakes Circle, Gulf Shores, AL 36542", year:"", city:"Gulf Shores", county:"Baldwin", state:"Alabama", region:"South AL", type:"Private", sites:110, hookup:"Full hookups, 50 amp only, concrete pads, cable/fiber WiFi", phone:"(251) 714-2709", web:"twolakesrvresort.com", tags:["Lakeside premium sites","Pool","Clubhouse","Pickleball"] },

  // ──────────────────────────────────────────────────────────
  //  NORTH CAROLINA  (10 parks)
  // ──────────────────────────────────────────────────────────

  { name:"Creekwood Farm RV Park", address:"4696 Jonathan Creek Rd, Waynesville, NC 28785", year:"", city:"Maggie Valley", county:"Haywood", state:"North Carolina", region:"Mountains NC", type:"Private", sites:55, hookup:"Full hookups, 30/50A, pull-throughs", phone:"(828) 926-7977", web:"creekwoodfarm.com", tags:["Nantahala NF gateway","Jonathan Creek","Cherokee area"] },
  { name:"Foxfire Mountain RV Sites", address:"1820 Tilson Rd, Murphy, NC 28906", year:"", city:"Murphy", county:"Cherokee", state:"North Carolina", region:"Mountains NC", type:"Private", sites:40, hookup:"Full hookups, 30/50A, WiFi", phone:"(828) 835-9706", web:"foxfiremountain.com", tags:["Western NC","Mountain views","Quiet"] },
  { name:"Mama Gertie's Hideaway Campground", address:"15 Uphill Rd, Swannanoa, NC 28778", year:"", city:"Swannanoa", county:"Buncombe", state:"North Carolina", region:"Mountains NC", type:"Private", sites:60, hookup:"Full hookups, 30/50A, WiFi", phone:"(828) 686-4258", web:"campmamagertie.com", tags:["Asheville area","River access","Hiking","Annual events"] },
  { name:"Black Bear Campground", address:"6192 Lake James Rd, Marion, NC 28752", year:"", city:"Marion", county:"McDowell", state:"North Carolina", region:"Mountains NC", type:"Private", sites:75, hookup:"Full hookups (W/E/S), 30/50A, pull-throughs", phone:"(828) 652-7928", web:"blackbearnc.com", tags:["Linville Gorge area","Lake Tahoma","Pool","WiFi"] },
  { name:"Bear Den Campground", address:"600 Bear Den Mountain Rd, Spruce Pine, NC 28777", year:"", city:"Spruce Pine", county:"Mitchell", state:"North Carolina", region:"Mountains NC", type:"Private", sites:95, hookup:"Full hookups, 30/50A, pull-throughs", phone:"(828) 765-2888", web:"beardencampground.com", tags:["Blue Ridge Pkwy area","Gem mining nearby","Pool","WiFi"] },
  { name:"Asheville West KOA", address:"309 Wiggins Rd, Candler, NC 28715", year:"", city:"Candler", county:"Buncombe", state:"North Carolina", region:"Mountains NC", type:"Private", sites:85, hookup:"Full hookups (W/E/S), 30/50A, WiFi", phone:"(828) 665-7015", web:"koa.com/campgrounds/asheville-west", tags:["Asheville area","Pool","Mountain views"] },
  { name:"Hound's Campground", address:"114 Raven Circle, Kings Mountain, NC 28086", year:"", city:"Gastonia", county:"Gaston", state:"North Carolina", region:"Piedmont NC", type:"Private", sites:45, hookup:"Full hookups, 30/50A", phone:"(704) 922-5723", web:"", tags:["Crowders Mountain area","Charlotte day trip"] },
  { name:"Jordan Lake Campground & Marina", address:"389 Fearrington Rd, Apex, NC 27502", year:"", city:"Pittsboro", county:"Chatham", state:"North Carolina", region:"Piedmont NC", type:"Private", sites:60, hookup:"Full hookups, 30/50A, WiFi", phone:"(919) 542-5600", web:"jordanlakecampground.com", tags:["Jordan Lake","Boat ramp","Fishing","Raleigh area"] },
  { name:"Cape Hatteras KOA Resort", address:"25099 NC Hwy 12, Rodanthe, NC 27968", year:"", city:"Rodanthe", county:"Dare", state:"North Carolina", region:"Coastal NC", type:"Private", sites:90, hookup:"Full hookups (W/E/S), 30/50A, WiFi, pool", phone:"(252) 987-2307", web:"koa.com/campgrounds/cape-hatteras", tags:["Outer Banks","Beach access","Kiteboarding","Fishing"] },
  { name:"Frisco Woods Campground", address:"53124 NC 12 Hwy, Frisco, NC 27936", year:"", city:"Frisco", county:"Dare", state:"North Carolina", region:"Coastal NC", type:"Private", sites:96, hookup:"Full hookups (W/E/S), 30/50A, WiFi", phone:"(252) 995-5208", web:"outer-banks.com/friscwoods", tags:["Outer Banks","Sound access","Windsurfing","Kiteboarding"] },

  // ──────────────────────────────────────────────────────────
  //  NORTH CAROLINA — LARGE PARKS, 100+ sites  (4 parks)
  // ──────────────────────────────────────────────────────────

  { name:"Camp Hatteras RV Resort", address:"24798 NC Hwy 12, Rodanthe, NC 27968", year:"", city:"Rodanthe", county:"Dare", state:"North Carolina", region:"Coastal NC", type:"Private", sites:403, hookup:"Full hookups (W/E/S), 30/50A, concrete pads", phone:"(252) 987-2777", web:"camphatteras.com", tags:["Outer Banks","Oceanfront to soundfront","Concrete pads","Big rig friendly"] },
  { name:"Cape Woods Campground", address:"47649 Buxton Back Rd, Buxton, NC 27920", year:"", city:"Buxton", county:"Dare", state:"North Carolina", region:"Coastal NC", type:"Private", sites:130, hookup:"Full and partial hookups (W/E/S), 30/50A, pull-throughs", phone:"(252) 996-3600", web:"capewoods.com", tags:["Outer Banks","Hatteras Island","Pool","Near Cape Hatteras Lighthouse"] },
  { name:"Camping World Racing Resort", address:"6600 Bruton Smith Blvd, Concord, NC 28027", year:"", city:"Concord", county:"Cabarrus", state:"North Carolina", region:"Piedmont NC", type:"Private", sites:380, hookup:"Full hookups (W/E/S), 30/50A", phone:"(704) 455-4445", web:"charlottemotorspeedway.com", tags:["Charlotte Motor Speedway","Year-round camping","Big rig friendly","NASCAR events nearby"] },
  { name:"Emerald Isle RV Resort", address:"9102 Coast Guard Rd, Emerald Isle, NC 28594", year:"", city:"Emerald Isle", county:"Carteret", state:"North Carolina", region:"Coastal NC", type:"Private", sites:313, hookup:"Full hookups, 30/50A, water, sewer, grassy pull-through sites", phone:"(252) 354-2250", web:"emeraldislervresort.com", tags:["Crystal Coast","Oceanfront","Pool","Big rig friendly"] },

  // ──────────────────────────────────────────────────────────
  //  SOUTH CAROLINA  (7 parks)
  // ──────────────────────────────────────────────────────────

  { name:"The Point at Lake Hartwell RV Resort", address:"400 Ponderosa Point Rd, Townville, SC 29689", year:"", city:"Townville", county:"Anderson", state:"South Carolina", region:"Upstate SC", type:"Private", sites:65, hookup:"Full hookups, 30/50A, waterfront sites", phone:"(864) 287-3376", web:"thepointatlakerv.com", tags:["Hartwell Lake","Boat ramp","Fishing","Swimming"] },
  { name:"Clemson RV Park at the Grove", address:"150 Dalton Dr, Pendleton, SC 29670", year:"", city:"Clemson", county:"Pickens", state:"South Carolina", region:"Upstate SC", type:"Private", sites:97, hookup:"Full hookups (W/E/S), 30/50A, paved pads", phone:"(864) 654-2626", web:"clemsonrv.com", tags:["Clemson area","Lake Hartwell access","WiFi","Year-round"] },
  { name:"River Bottom Farms Campground", address:"357 Cedar Creek Rd, Swansea, SC 29160", year:"", city:"Leesville", county:"Lexington", state:"South Carolina", region:"Midlands SC", type:"Private", sites:75, hookup:"Full hookups, 30/50A, pull-throughs", phone:"(803) 532-2854", web:"riverbottomfarms.com", tags:["Lake Murray area","Farm setting","Pool","Columbia day trip"] },
  { name:"Edmund RV Park", address:"5910 Edmund Hwy, Lexington, SC 29073", year:"", city:"Edmund", county:"Lexington", state:"South Carolina", region:"Midlands SC", type:"Private", sites:50, hookup:"Full hookups (W/E/S), 30/50A", phone:"(803) 732-0888", web:"", tags:["Congaree NP nearby","Lake Murray area","Monthly rates"] },
  { name:"Sesquicentennial State Park - Camp Lake Adger", address:"9564 Two Notch Rd, Columbia, SC 29223", year:"", city:"Columbia", county:"Richland", state:"South Carolina", region:"Midlands SC", type:"Private", sites:87, hookup:"Full hookups, 30/50A, WiFi", phone:"(803) 788-2706", web:"", tags:["Columbia area","Lake","Fishing","Quiet pines"] },
  { name:"Oaks at Point South RV Resort", address:"1292 Campground Rd, Yemassee, SC 29945", year:"", city:"Yemassee", county:"Hampton", state:"South Carolina", region:"Lowcountry SC", type:"Private", sites:95, hookup:"Full hookups (W/E/S), 30/50A, pull-throughs", phone:"(843) 726-5728", web:"oaksatpointsouth.com", tags:["I-95 corridor","Hilton Head day trip","Pool","WiFi"] },
  { name:"Savannah Lakes RV Resort", address:"170 Savannah Lakes Dr, Hardeeville, SC 29927", year:"", city:"Hardeeville", county:"Jasper", state:"South Carolina", region:"Lowcountry SC", type:"Private", sites:90, hookup:"Full hookups (W/E/S), 30/50A, WiFi", phone:"(843) 784-2313", web:"savannahlakesrv.com", tags:["Near Savannah GA","Pool","Hot tub","Birding"] },

  // ──────────────────────────────────────────────────────────
  //  SOUTH CAROLINA — LARGE PARKS, 100+ sites  (5 parks)
  // ──────────────────────────────────────────────────────────

  { name:"Ocean Lakes Family Campground", address:"6001 South Kings Hwy, Myrtle Beach, SC 29575", year:"", city:"Myrtle Beach", county:"Horry", state:"South Carolina", region:"Grand Strand SC", type:"Private", sites:859, hookup:"20/30/50A electric, water, sewer, cable TV, concrete pads on most sites", phone:"(877) 510-1413", web:"oceanlakes.com", tags:["Oceanfront","One-mile beachfront","Family campground","Big rig friendly"] },
  { name:"Lakewood Camping Resort", address:"5901 S Kings Hwy, Myrtle Beach, SC 29575", year:"", city:"Myrtle Beach", county:"Horry", state:"South Carolina", region:"Grand Strand SC", type:"Private", sites:1043, hookup:"Full hookups, 20/30/50A, water, sewer", phone:"(843) 238-5161", web:"lakewoodcampground.com", tags:["Oceanfront","Lakefront sites","Water park","Pet-friendly"] },
  { name:"WillowTree RV Resort", address:"520 Southern Sights Dr, Longs, SC 29568", year:"", city:"Longs", county:"Horry", state:"South Carolina", region:"Grand Strand SC", type:"Private", sites:107, hookup:"Full hookups, 20/30/50A, paved pull-through sites", phone:"(843) 756-4334", web:"willowtreervr.com", tags:["Paved pull-throughs","Big rig friendly","Fire rings","Concrete patios"] },
  { name:"Hilton Head Island Motorcoach Resort", address:"133 Arrow Rd, Hilton Head Island, SC 29928", year:"", city:"Hilton Head Island", county:"Beaufort", state:"South Carolina", region:"Lowcountry SC", type:"Private", sites:401, hookup:"Full hookups, 30/50A, water, sewer, cable TV (motorcoach only)", phone:"(843) 785-7699", web:"hhimotorcoachresort.com", tags:["Motorcoach-only resort","Gated","Pool & hot tub","Pickleball","Dog park"] },
  { name:"Oak Plantation Campground", address:"3540 Savannah Hwy, Johns Island, SC 29455", year:"", city:"Johns Island", county:"Charleston", state:"South Carolina", region:"Lowcountry SC", type:"Private", sites:298, hookup:"20/30/50A, full-hookup and pull-through sites", phone:"(843) 766-5936", web:"oakplantationcampground.com", tags:["Near Charleston","Pull-through sites","Pool","Big rig friendly"] },

  // ──────────────────────────────────────────────────────────
  //  TEXAS  (125 parks)
  // ──────────────────────────────────────────────────────────

  { name:"Dos Rios RV Park", address:"4500 Dos Rios Trail, Mason, TX 76856", year:"", city:"Mason", county:"Mason", state:"Texas", region:"Hill Country TX", type:"Private", sites:19, hookup:"Full hookups, riverfront sites", phone:"(512) 553-3977", web:"dosriosrvpark.com", tags:["Llano River","Dog-friendly","Stargazing","Fredericksburg nearby"] },
  { name:"Nestled Pines RV Park", address:"458 County Rd 466, Etoile, TX 75944", year:"", city:"Etoile", county:"Nacogdoches", state:"Texas", region:"East TX", type:"Private", sites:15, hookup:"Full hookups, 20/30/50A, fiber WiFi", phone:"(936) 556-0012", web:"nestledpinesrvpark.com", tags:["Piney Woods","Lake Sam Rayburn","Small park","Quiet"] },
  { name:"The Pines RV & Cabin Resort", address:"4069 County Rd SE 4250, Mount Vernon, TX 75457", year:"", city:"Mount Vernon", county:"Franklin", state:"Texas", region:"East TX", type:"Private", sites:65, hookup:"Full hookups, concrete pads, pull-throughs", phone:"(903) 860-2680", web:"thepinesrvcabinresort.com", tags:["Lake Cypress Springs","Lake Bob Sandlin","Pool","Dog parks"] },
  { name:"Shady Hill RV Park", address:"10700 Jacksboro Hwy, Fort Worth, TX 76135", year:"", city:"Fort Worth", county:"Tarrant", state:"Texas", region:"North TX", type:"Private", sites:60, hookup:"Full hookups, paved sites", phone:"(817) 229-3817", web:"shadyhillrvpark.com", tags:["Lake Worth","Eagle Mountain Lake","Shade trees"] },
  { name:"Pecan Acres RV Park", address:"12667 S FM 730, Azle, TX 76020", year:"", city:"Azle", county:"Tarrant", state:"Texas", region:"North TX", type:"Private", sites:84, hookup:"Full hookups, 30/50A", phone:"(817) 688-9316", web:"pecanacresrvpark.net", tags:["Pecan grove","Fort Worth area","Shaded sites"] },
  { name:"Cotton Land RV Park", address:"5040 E Hwy 62-82, Lubbock, TX 79403", year:"", city:"Lubbock", county:"Lubbock", state:"Texas", region:"Panhandle TX", type:"Private", sites:25, hookup:"Electric + water, back-in and pull-through", phone:"(806) 319-5280", web:"cottonlandrv.com", tags:["Family-owned","Laundry facility"] },
  { name:"Triangle RV Park", address:"500 Orient St, Claude, TX 79019", year:"", city:"Claude", county:"Armstrong", state:"Texas", region:"Panhandle TX", type:"Private", sites:30, hookup:"Full hookups, 30/50A, water", phone:"(806) 433-5671", web:"trianglervpark.com", tags:["Near Amarillo","Pet friendly","24-hour access"] },
  { name:"Overnite RV Park", address:"900 S Lakeside Dr, Amarillo, TX 79118", year:"", city:"Amarillo", county:"Potter", state:"Texas", region:"Panhandle TX", type:"Private", sites:79, hookup:"Full hookups, pull-through sites", phone:"(806) 373-1431", web:"overnitervpark.com", tags:["I-40 corridor","Long-term stays","Route 66"] },
  { name:"Hackberry Acres RV Park", address:"403 Hackberry St, Clifton, TX 76634", year:"", city:"Clifton", county:"Bosque", state:"Texas", region:"Central TX", type:"Private", sites:22, hookup:"Full hookups, 20/30/50A, pull-throughs", phone:"(254) 633-3363", web:"hackberryacresrvpark.com", tags:["Bosque River","Walkable downtown","Big-rig friendly"] },

  { name:"Texas Gulf RV Park", address:"115 N Byers Dr, Port O'Connor, TX 77982", year:"", city:"Port O'Connor", county:"Calhoun", state:"Texas", region:"Gulf Coast TX", type:"Private", sites:27, hookup:"Full hookups, 20/30/50 amp electric", phone:"", web:"", tags:["Small in-town park","Near Port O'Connor harbor","Matagorda Bay fishing"] },
  { name:"Port O'Connor RV Park", address:"110 Steve Street, Port O'Connor, TX 77982", year:"", city:"Port O'Connor", county:"Calhoun", state:"Texas", region:"Gulf Coast TX", type:"Private", sites:71, hookup:"Full hookups, 50/30/20 amp", phone:"(361) 484-9737", web:"pocrvp.com", tags:["Swimming pool & hot tub","Near Matagorda Bay","Gulf Coast fishing town"] },
  { name:"Beacon 44 RV Park", address:"1982 W. Harrison Ave, Port O'Connor, TX 77982", year:"", city:"Port O'Connor", county:"Calhoun", state:"Texas", region:"Gulf Coast TX", type:"Private", sites:50, hookup:"30/50 amp electric, water, sewer, gravel pads", phone:"(361) 983-4247", web:"beacon44rvpark.com", tags:["Stocked fishing pond","Near Matagorda Island","Off Highway 185"] },
  { name:"Caney Creek RV Park", address:"230 County Road 285, Sargent, TX 77414", year:"", city:"Sargent", county:"Matagorda", state:"Texas", region:"Gulf Coast TX", type:"Private", sites:32, hookup:"Full hookups, 30/50 amp, concrete pads", phone:"(979) 245-4735", web:"caneycreekrv.com", tags:["Boat ramp & fish cleaning station","Family owned since 2001","Caney Creek access"] },
  { name:"Sargent Beach RV Park", address:"27466 FM 457, Sargent, TX 77414", year:"", city:"Sargent", county:"Matagorda", state:"Texas", region:"Gulf Coast TX", type:"Private", sites:7, hookup:"30/50 amp electric, water, sewer", phone:"(979) 529-5295", web:"sargentbeachrvpark.com", tags:["Directly on Sargent Beach","Between Gulf and Intracoastal Waterway","Concrete pads, big-rig friendly"] },

  { name:"RV Haven", address:"922 Mack Rd, Aransas Pass, TX 78336", year:"", city:"Aransas Pass", county:"San Patricio", state:"Texas", region:"Coastal Bend TX", type:"Private", sites:14, hookup:"Full hookups, 30/50/110 amp", phone:"(361) 238-5483", web:"rvhavenrockport.com", tags:["Near Rockport & Port Aransas","Oak-shaded sites","Small quiet retreat"] },
  { name:"Live Oak Point RV Park", address:"4730 Texas Business 35 N, Rockport, TX 78382", year:"", city:"Rockport", county:"Aransas", state:"Texas", region:"Coastal Bend TX", type:"Private", sites:23, hookup:"Water, electric, sewer (septic), concrete pads", phone:"(361) 238-0995", web:"liveoakpointrv.com", tags:["Aransas Bay waterfront","Long fishing pier","Dog-friendly","Near Copano Bridge"] },
  { name:"Driftwood RV Park", address:"701 Mesquite St, Fulton, TX 78358", year:"", city:"Fulton", county:"Aransas", state:"Texas", region:"Coastal Bend TX", type:"Private", sites:56, hookup:"Full hookups", phone:"(361) 729-2452", web:"driftwoodrvrockport.com", tags:["Close to Aransas Bay","Near downtown Rockport-Fulton"] },
  { name:"Sunrise RV Resort", address:"701 Myrtle St, Fulton, TX 78358", year:"", city:"Fulton", county:"Aransas", state:"Texas", region:"Coastal Bend TX", type:"Private", sites:79, hookup:"Full hookups, 30/50 amp, pull-through sites", phone:"(361) 360-4822", web:"sunriservresort.com", tags:["Half mile from downtown Fulton","3 miles to Rockport Beach","Pool"] },
  { name:"Coastal Cowboy RV Park - Fulton", address:"3639 TX-35, Rockport, TX 78382", year:"", city:"Rockport", county:"Aransas", state:"Texas", region:"Coastal Bend TX", type:"Private", sites:39, hookup:"Full hookups, 20/30/50 amp, pull-thrus", phone:"(361) 775-5230", web:"coastalcowboyrvpark.com", tags:["Aransas Bay views","Near Fulton","Activity center"] },

  { name:"D&L RV Park", address:"151 Minnesota Rd, Alamo, TX 78516", year:"", city:"Alamo", county:"Hidalgo", state:"Texas", region:"Rio Grande Valley TX", type:"Private", sites:9, hookup:"Full hookups, 30/50 amp, paved roads", phone:"(956) 929-4154", web:"", tags:["Tiny park","Home-style RV park","Pet friendly","Shuffleboard"] },
  { name:"Monte Cristo Golf & Country Club RV Park", address:"2919 N Kenyon Rd, Edinburg, TX 78542", year:"", city:"Edinburg", county:"Hidalgo", state:"Texas", region:"Rio Grande Valley TX", type:"Private", sites:20, hookup:"Full hookups, 30/50 amp", phone:"(866) 576-5333", web:"montecristogcc.com", tags:["Golf course access","Clubhouse","Swimming pool","55+ friendly"] },
  { name:"Sundance RV Village", address:"6101 W Business 83, Harlingen, TX 78552", year:"", city:"Harlingen", county:"Cameron", state:"Texas", region:"Rio Grande Valley TX", type:"Private", sites:77, hookup:"Full hookups, 30/50 amp, pull-through sites", phone:"(956) 423-8314", web:"sundancervresort.com", tags:["Gated","Clubhouse","Shuffleboard","Big rig friendly"] },
  { name:"La Floresta RV Park & Golf Course", address:"4140 La Floresta, Mercedes, TX 78570", year:"", city:"Mercedes", county:"Hidalgo", state:"Texas", region:"Rio Grande Valley TX", type:"Private", sites:92, hookup:"Full hookups, 30/50 amp", phone:"(956) 565-6314", web:"laflorestarvpark.com", tags:["Golf course","Historic 1929 estate grounds","Clubhouse","55+ community"] },

  { name:"Terlingua Ranch Lodge RV Park", address:"16000 Terlingua Ranch Rd, Terlingua, TX 79852", year:"", city:"Terlingua", county:"Brewster", state:"Texas", region:"Big Bend TX", type:"Private", sites:20, hookup:"15/20/30/50 amp electric, water, sewer at pull-throughs", phone:"(432) 371-3146", web:"terlinguaranch.com", tags:["Near Big Bend National Park","Pool and restaurant","Mountain views"] },
  { name:"Tumble In RV Park", address:"93320 US Hwy 90 E, Marfa, TX 79843", year:"", city:"Marfa", county:"Presidio", state:"Texas", region:"Big Bend TX", type:"Private", sites:22, hookup:"20/30/50 amp electric, water, some sewer, dump station", phone:"(432) 301-9860", web:"tumbleinmarfa.com", tags:["Locally owned","Level gravel sites","Free WiFi","Near Marfa Lights"] },
  { name:"Study Butte RV Park", address:"53751 TX-118, Terlingua, TX 79852", year:"", city:"Terlingua", county:"Brewster", state:"Texas", region:"Big Bend TX", type:"Private", sites:10, hookup:"Full hookups, 30 amp, RVs only up to 40 ft", phone:"(432) 371-2468", web:"", tags:["Closest RV park to Big Bend NP entrance","RV-only park","On-site store"] },
  { name:"Marathon Motel & RV Park", address:"701 US-90, Marathon, TX 79842", year:"", city:"Marathon", county:"Brewster", state:"Texas", region:"Big Bend TX", type:"Private", sites:29, hookup:"Full hookups", phone:"(432) 386-4241", web:"marathonmotel.com", tags:["Motel and RV combo","Gateway to Big Bend","Historic Marathon"] },
  { name:"Cliffhanger RV Park", address:"45978 State Highway 118 S, Alpine, TX 79830", year:"", city:"Alpine", county:"Brewster", state:"Texas", region:"Big Bend TX", type:"Private", sites:6, hookup:"Full hookups, 30/50 amp, dump station, max 50 ft", phone:"", web:"", tags:["Small 6-site park","Rustic, off-the-beaten-path","Pet friendly"] },

  { name:"Cactus Draw R.V. Park", address:"1306 North Birdwell Lane, Big Spring, TX 79720", year:"", city:"Big Spring", county:"Howard", state:"Texas", region:"Permian Basin TX", type:"Private", sites:17, hookup:"Full hookups, 30/50 amp", phone:"(817) 205-8138", web:"cactusdrawrv.com", tags:["North of I-20","Nestled in trees","13 acres of trails","Cabin rentals"] },
  { name:"Our Place RV Park", address:"6804 South Service Road, Big Spring, TX 79720", year:"", city:"Big Spring", county:"Howard", state:"Texas", region:"Permian Basin TX", type:"Private", sites:20, hookup:"Full hookups, 30/50 amp, pull-through", phone:"(432) 287-1302", web:"", tags:["Pull-through sites","On I-20 service road","Dog park","Strong WiFi"] },
  { name:"Gil's RV Korral", address:"7105 Grape Creek Road, San Angelo, TX 76901", year:"", city:"San Angelo", county:"Tom Green", state:"Texas", region:"Permian Basin TX", type:"Private", sites:14, hookup:"Full hookups, 30/50 amp, no dump station", phone:"(325) 277-6847", web:"", tags:["24-hour access","On-site laundromat","Long-term stays"] },
  { name:"Castaway RV Park", address:"7551 West 26th Street, Odessa, TX 79763", year:"", city:"Odessa", county:"Ector", state:"Texas", region:"Permian Basin TX", type:"Private", sites:20, hookup:"Full hookups, 30/50 amp", phone:"(432) 381-5552", web:"castawayrvparks.com", tags:["Family operated","Quiet & private","Shaded sites"] },

  { name:"Yanawana Camp", address:"2322 E Chavaneaux Rd, San Antonio, TX 78214", year:"", city:"San Antonio", county:"Bexar", state:"Texas", region:"South TX", type:"Private", sites:5, hookup:"Full hookups, 20/30/50 amp, gravel back-in sites", phone:"(512) 496-8893", web:"yanawanacamp.com", tags:["Near Mission San Juan","San Antonio Missions Trail","2.4 acres","Pet friendly"] },
  { name:"Rio Guadalupe Resort", address:"14130 River Rd, New Braunfels, TX 78132", year:"", city:"New Braunfels", county:"Comal", state:"Texas", region:"South TX", type:"Private", sites:64, hookup:"Full hookups, 30/50 amp, cable, WiFi", phone:"(830) 964-3613", web:"rioguadaluperesort.com", tags:["Guadalupe River frontage","Tubing & kayaking","Near Canyon Lake","Open since 1976"] },
  { name:"Little RV Spot", address:"1574 Westward Trail, Uvalde, TX 78801", year:"", city:"Uvalde", county:"Uvalde", state:"Texas", region:"South TX", type:"Private", sites:22, hookup:"Full hookups, 30/50 amp, gravel back-in sites", phone:"(830) 931-5109", web:"thelittlervspot.com", tags:["Big rig friendly","Self-service RV wash","Near Frio River"] },
  { name:"Hidden Valley RV Park", address:"5706 Coleman Way, Von Ormy, TX 78073", year:"", city:"Von Ormy", county:"Bexar", state:"Texas", region:"South TX", type:"Private", sites:74, hookup:"Full hookups, 30/50 amp, concrete & gravel pads", phone:"(210) 623-6737", web:"hiddenvalleyrvpark.com", tags:["Medio Creek frontage","Dog park","2025 Campspot Award winner"] },
  { name:"The Dam Park", address:"961 Lakeside Pass, New Braunfels, TX 78130", year:"", city:"New Braunfels", county:"Comal", state:"Texas", region:"South TX", type:"Private", sites:45, hookup:"Full hookups, WiFi included", phone:"(830) 282-0662", web:"thedampark.com", tags:["Guadalupe River access","Riverfront cabanas","Locally owned","Dog park"] },

  { name:"Tall Timbers RV Park", address:"16614 Echo Glen Dr, Tyler, TX 75703", year:"", city:"Tyler", county:"Smith", state:"Texas", region:"East TX", type:"Private", sites:14, hookup:"Full hookups, concrete pads, 30/50A", phone:"(903) 871-5760", web:"ttrv.com", tags:["South Tyler","Concrete pads","All bills paid","Small park"] },
  { name:"Buffalo Run RV Park", address:"1800 US Highway 59 N, Jefferson, TX 75657", year:"", city:"Jefferson", county:"Marion", state:"Texas", region:"East TX", type:"Private", sites:28, hookup:"Full hookups, 30/50A, pull-through sites", phone:"(903) 665-4250", web:"buffalorunrvpark.net", tags:["Near Caddo Lake","Historic Jefferson","Pull-through","Pet friendly"] },
  { name:"Home Sweet Home RV Park", address:"6451 W 7th St, Texarkana, TX 75501", year:"", city:"Texarkana", county:"Bowie", state:"Texas", region:"East TX", type:"Private", sites:48, hookup:"Full hookups, 30/50A", phone:"(903) 838-4462", web:"homesweethomervpark.com", tags:["I-30 access","RV-only park","Pet friendly"] },
  { name:"Cypress Valley RV Park", address:"8838 US Highway 59 N, Marshall, TX 75670", year:"", city:"Marshall", county:"Harrison", state:"Texas", region:"East TX", type:"Private", sites:57, hookup:"Full hookups, 20/30/50A, pull-through sites", phone:"(903) 938-8844", web:"cypressvalleyrvparktx.com", tags:["Near Jefferson","Fishing pond","Big rig friendly"] },
  { name:"Southern Pines RV Campground", address:"5264 Ted Trout Dr, Lufkin, TX 75904", year:"", city:"Lufkin", county:"Angelina", state:"Texas", region:"East TX", type:"Private", sites:33, hookup:"Full hookups, 100% concrete pads, 20/30/50A", phone:"(903) 707-0660", web:"southernpinesrvcampground.com", tags:["100% concrete pads","Dog park","Pool","Pet friendly"] },

  { name:"Cozy Hill RV and Cabin Resort", address:"2110 N FM 51, Weatherford, TX 76086", year:"", city:"Weatherford", county:"Parker", state:"Texas", region:"North TX", type:"Private", sites:48, hookup:"Full hookups, 20/30/50 amp", phone:"(817) 408-0800", web:"cozyhillrvandcabinresort.com", tags:["Pond","Creek frontage","Cabin rentals","Walking trails"] },
  { name:"Hooves N Wheels RV Park & Horse Motel", address:"4128 Granbury Hwy, Weatherford, TX 76087", year:"", city:"Weatherford", county:"Parker", state:"Texas", region:"North TX", type:"Private", sites:52, hookup:"Full hookups, 30/50 amp, pull-through and back-in", phone:"(817) 599-4686", web:"hoovesnwheels.com", tags:["Horse motel","Family owned","Dog park","Big rig friendly"] },
  { name:"Rockett RV Ranch", address:"3160 FM 813, Palmer, TX 75152", year:"", city:"Palmer", county:"Ellis", state:"Texas", region:"North TX", type:"Private", sites:36, hookup:"Full hookups, 20/30/50 amp, hard-surface sites", phone:"(469) 658-6557", web:"rockettrvranch.com", tags:["Clubhouse","Near Waxahachie","Daily laundry","Free WiFi"] },
  { name:"McWest RV Park", address:"727 E Cottage Hill Pkwy, McKinney, TX 75071", year:"", city:"McKinney", county:"Collin", state:"Texas", region:"North TX", type:"Private", sites:30, hookup:"Water/sewer hookups, 20/30/50 amp, back-in sites", phone:"(214) 714-4318", web:"mcwestrvpark.com", tags:["Back-in sites","Pet friendly","Collin County"] },

  { name:"Buddy's Backyard RV Resort", address:"401 Stagecoach Ranch Rd, Dripping Springs, TX 78620", year:"", city:"Dripping Springs", county:"Travis", state:"Texas", region:"Austin Area TX", type:"Private", sites:75, hookup:"Full hookups, 30/50 amp", phone:"(512) 800-8033", web:"buddysbackyardrv.com", tags:["Hill Country views","Pool & clubhouse","Pet friendly"] },
  { name:"Pecan Grove RV Park", address:"1518 Barton Springs Rd, Austin, TX 78704", year:"", city:"Austin", county:"Travis", state:"Texas", region:"Austin Area TX", type:"Private", sites:93, hookup:"Full hookups, 30/50 amp", phone:"(512) 472-1067", web:"", tags:["Walk to Zilker Park","Near Barton Springs Pool","Shaded by pecan trees","Downtown Austin"] },
  { name:"Riverbend RV Park on Lake Austin", address:"12405 River Bend, Austin, TX 78732", year:"", city:"Austin", county:"Travis", state:"Texas", region:"Austin Area TX", type:"Private", sites:5, hookup:"Full hookup pads", phone:"(512) 694-0094", web:"riverbendaustin.com", tags:["Lake Austin waterfront","Kayak access","Tiny 5-site park"] },
  { name:"Reagan Ridge RV Park", address:"26690 Ronald W Reagan Blvd, Georgetown, TX 78633", year:"", city:"Georgetown", county:"Williamson", state:"Texas", region:"Austin Area TX", type:"Private", sites:71, hookup:"Full hookups, 20/30/50 amp, city water", phone:"(512) 829-0033", web:"reaganridgerv.com", tags:["Adult-focused, quiet","Pool","Free WiFi"] },

  { name:"Abilene RV Park", address:"6195 E Hwy 80, Abilene, TX 79601", year:"", city:"Abilene", county:"Taylor", state:"Texas", region:"Panhandle TX", type:"Private", sites:66, hookup:"Full hookups, 30/50 amp, pull-thru sites", phone:"(325) 672-2212", web:"abilenetexasrvpark.com", tags:["Swimming pool","Laundry","Pet-friendly"] },
  { name:"Shady Lane RV Park", address:"2010 East 5th Street, Plainview, TX 79072", year:"", city:"Plainview", county:"Hale", state:"Texas", region:"Panhandle TX", type:"Private", sites:48, hookup:"Full hookups, 20/30/50 amp", phone:"(806) 518-5985", web:"shadylanervparktx.com", tags:["Family-owned","Shade trees","24/7 on-site managers"] },
  { name:"Back Forty RV Park", address:"2062 FM 2568, Quanah, TX 79252", year:"", city:"Quanah", county:"Hardeman", state:"Texas", region:"Panhandle TX", type:"Private", sites:40, hookup:"Full hookups, 30/50 amp, gravel pads", phone:"(940) 839-8874", web:"backfortyrv.com", tags:["Veteran-owned","Near Childress","Big-rig friendly"] },
  { name:"Rocking A RV Park", address:"3725 Harrison St, Vernon, TX 76384", year:"", city:"Vernon", county:"Wilbarger", state:"Texas", region:"Panhandle TX", type:"Private", sites:77, hookup:"Full hookups, 30/50 amp, pull-thru grass sites", phone:"(940) 552-2821", web:"rockingarvpark.com", tags:["Shade trees","Swimming pool","Near Wichita Falls"] },

  { name:"Greyhound RV Park", address:"5402 Leopard St, Corpus Christi, TX 78408", year:"", city:"Corpus Christi", county:"Nueces", state:"Texas", region:"Coastal Bend TX", type:"Private", sites:90, hookup:"Full hookups, 30/50 amp, 50 pull-through sites", phone:"(361) 289-2076", web:"", tags:["Central location","Pull-through sites","Big rig friendly to 60 ft"] },
  { name:"Padre Palms RV Park", address:"131 Skipper Lane, Corpus Christi, TX 78412", year:"", city:"Corpus Christi", county:"Nueces", state:"Texas", region:"Coastal Bend TX", type:"Private", sites:81, hookup:"Full hookups, 30/50 amp sites", phone:"(361) 937-2125", web:"padrepalmsrvresort.com", tags:["Near Padre Island","LP gas delivery"] },
  { name:"Reed's RV Park", address:"633 E County Rd 44, Robstown, TX 78380", year:"", city:"Robstown", county:"Nueces", state:"Texas", region:"Coastal Bend TX", type:"Private", sites:52, hookup:"Full hookups, paved parking spurs", phone:"(361) 726-9339", web:"reedscorpuschristi.com", tags:["Fishing pond","Private gym","Laundry room"] },
  { name:"Portland RV Park", address:"601 US Hwy 181, Portland, TX 78374", year:"", city:"Portland", county:"San Patricio", state:"Texas", region:"Coastal Bend TX", type:"Private", sites:26, hookup:"Full hookups, 30/50 amp, waterfront gravel/grass sites", phone:"(361) 202-9002", web:"corpuschristiboardwalkrvpark.com", tags:["Waterfront","Extended stay","Near Corpus Christi Bay"] },

  { name:"Arvey RV Park", address:"11200 Montana Ave, El Paso, TX 79936", year:"", city:"El Paso", county:"El Paso", state:"Texas", region:"El Paso TX", type:"Private", sites:40, hookup:"Full hookups, electric-only, and electric/water sites; pull-throughs", phone:"(915) 598-7522", web:"", tags:["Pull-through sites","Laundry & showers","East El Paso"] },
  { name:"Great Escapes RV Resort El Paso", address:"901 S Leisure Fun Rd, Anthony, TX 79821", year:"", city:"Anthony", county:"El Paso", state:"Texas", region:"El Paso TX", type:"Private", sites:92, hookup:"Full hookups, 20/30/50 amp electric, level gravel pull-through sites", phone:"(915) 603-3105", web:"greatescapesrvresorts.com", tags:["Off I-10","Level gravel sites","80-ft pull-throughs"] },
  { name:"Gaslight Square Mobile Home & RV Park", address:"500 Talbot Ave, Canutillo, TX 79835", year:"", city:"Canutillo", county:"El Paso", state:"Texas", region:"El Paso TX", type:"Private", sites:23, hookup:"Full hookups, 30/50 amp electric, water and sewer", phone:"(915) 877-2238", web:"gaslightsquaremhc.com", tags:["Mobile home & RV community","Swimming pool","Near NM border"] },
  { name:"Desert Oasis Park", address:"12705 Montana Ave, El Paso, TX 79938", year:"", city:"El Paso", county:"El Paso", state:"Texas", region:"El Paso TX", type:"Private", sites:33, hookup:"Full hookups - water, sewer, electric", phone:"(915) 855-3366", web:"desertoasistexas.com", tags:["Short & long-term stays","East El Paso"] },
  { name:"Mission Trail Mobile Home & RV Park", address:"8479 Alameda Ave, El Paso, TX 79907", year:"", city:"El Paso", county:"El Paso", state:"Texas", region:"El Paso TX", type:"Private", sites:15, hookup:"Full hookups, 50 amp electric, water and sewer", phone:"(915) 859-0202", web:"", tags:["Clubhouse & playground","Pet-friendly"] },
  { name:"Southern Star RV Park", address:"1605 W Broadway St, Van Horn, TX 79855", year:"", city:"Van Horn", county:"Culberson", state:"Texas", region:"El Paso TX", type:"Private", sites:46, hookup:"Full hookups, 30/50 amp electric, gravel pull-throughs", phone:"(432) 283-2420", web:"southernstarrv.com", tags:["I-10 overnight stop","Recreation hall","Dog park"] },
  { name:"Van Horn RV Park", address:"10 Kampers Lane, Van Horn, TX 79855", year:"", city:"Van Horn", county:"Culberson", state:"Texas", region:"El Paso TX", type:"Private", sites:74, hookup:"Full hookups, pull-through sites", phone:"(432) 283-2728", web:"vanhorntexasrvpark.com", tags:["Big rig friendly","Swimming pool","Horse corrals"] },

  { name:"Bird Creek RV Park", address:"1222 Sioux, Temple, TX 76504", year:"", city:"Temple", county:"Bell", state:"Texas", region:"Central TX", type:"Private", sites:31, hookup:"Full hookups, pull-through sites, cable TV", phone:"(254) 773-9431", web:"", tags:["Pull-through sites","Big rig friendly","Near I-35","Pool"] },
  { name:"Gatesville RV Park", address:"2400 Texas 36 Business, Gatesville, TX 76528", year:"", city:"Gatesville", county:"Coryell", state:"Texas", region:"Central TX", type:"Private", sites:18, hookup:"Full hookups, pull-through sites, electric, water, cable TV", phone:"(254) 248-2008", web:"", tags:["In-town location","Pull-through sites","Pet friendly"] },
  { name:"Sunset Ridge RV Park", address:"9515 FM 2657, Kempner, TX 76539", year:"", city:"Kempner", county:"Lampasas", state:"Texas", region:"Central TX", type:"Private", sites:40, hookup:"Full hookups (water, sewer, electric)", phone:"(737) 210-1703", web:"sunsetridgervparktx.com", tags:["Cabins & tiny homes on-site","Dog park","Military discount","Near Fort Cavazos/Killeen"] },
  { name:"Cove RV Park", address:"402 W Highway 190, Copperas Cove, TX 76522", year:"", city:"Copperas Cove", county:"Coryell", state:"Texas", region:"Central TX", type:"Private", sites:33, hookup:"Full hookups, 30/50 amp, pull-through sites", phone:"(254) 290-3816", web:"covervpark.com", tags:["Pull-through sites","Big rig friendly","Pet friendly"] },
  { name:"Flat Creek Farms RV Resort", address:"1633 Greig Dr, Waco, TX 76706", year:"", city:"Waco", county:"McLennan", state:"Texas", region:"Central TX", type:"Private", sites:78, hookup:"Full hookups, 20/30/50 amp, water, sewer", phone:"(254) 662-9858", web:"flatcreekfarmsrvresort.com", tags:["78-acre resort","Midway Dallas-Austin","Near I-35"] },
  { name:"Clear Creek RV Park", address:"3215 FM 2657, Copperas Cove, TX 76522", year:"", city:"Copperas Cove", county:"Coryell", state:"Texas", region:"Central TX", type:"Private", sites:57, hookup:"Full hookups, 30/50 amp, water, sewer", phone:"(512) 566-6842", web:"clearcreekparkrv.com", tags:["Dog park","High-speed internet","Pet friendly"] },
  { name:"Joy Drive In Movie & RV Resort", address:"3196 Renee St, Copperas Cove, TX 76522", year:"", city:"Copperas Cove", county:"Coryell", state:"Texas", region:"Central TX", type:"Private", sites:82, hookup:"Full hookups, 30/50 amp electric, water, sewer", phone:"(254) 238-7232", web:"joyrv.org", tags:["17.3-acre resort","On-site drive-in movie theater","Dog park"] },

  { name:"Dominion Oaks RV Park", address:"10586 Marbach Road, San Antonio, TX 78245", year:"", city:"San Antonio", county:"Bexar", state:"Texas", region:"South TX", type:"Private", sites:40, hookup:"Full hookups", phone:"(210) 201-3701", web:"dominionoaksrvpark.com", tags:["Free WiFi","Laundry","Weekly/monthly rentals"] },
  { name:"Camp Huaco Springs", address:"4150 River Road, New Braunfels, TX 78132", year:"", city:"New Braunfels", county:"Comal", state:"Texas", region:"South TX", type:"Private", sites:75, hookup:"Full hookups, 30/50 amp electric", phone:"(830) 625-5411", web:"camphuacosprings.com", tags:["Guadalupe River frontage","Tubing","Cabins available"] },
  { name:"River Ranch RV Resort", address:"420 N. Business I-35, New Braunfels, TX 78130", year:"", city:"New Braunfels", county:"Comal", state:"Texas", region:"South TX", type:"Private", sites:54, hookup:"Full hookups", phone:"(830) 625-7788", web:"riverranchtexas.com", tags:["Cable TV","Laundry","Sports field"] },
  { name:"Patriot RV Park - Seguin", address:"3311 US Hwy 90 West, Seguin, TX 78155", year:"", city:"Seguin", county:"Guadalupe", state:"Texas", region:"South TX", type:"Private", sites:40, hookup:"Full hookups, 30/50 amp electric, water, sewer", phone:"(830) 212-4836", web:"patriotrvparks.com", tags:["Near Guadalupe River","Pet friendly","Cable TV"] },
  { name:"Cascade Caverns Campground", address:"226 Cascade Caverns Rd, Boerne, TX 78015", year:"", city:"Boerne", county:"Kendall", state:"Texas", region:"South TX", type:"Private", sites:95, hookup:"30/50 amp sites, water, sewer", phone:"(830) 755-8080", web:"cascadecaverns.com", tags:["Show cave on site","Big rig access","RV storage"] },

  { name:"Lost Lake RV Park", address:"1222 Jeffcote Road, Conroe, TX 77303", year:"", city:"Conroe", county:"Montgomery", state:"Texas", region:"Houston Metro TX", type:"Private", sites:90, hookup:"Full hookups, 50 amp electric, water, sewer", phone:"(936) 777-5289", web:"lostlakerv.com", tags:["Gated 30-acre community","Stocked fishing pond","Near Sam Houston National Forest","Free WiFi"] },
  { name:"Cut N Shoot RV Park", address:"18987 FM 1484, Conroe, TX 77303", year:"", city:"Conroe", county:"Montgomery", state:"Texas", region:"Houston Metro TX", type:"Private", sites:40, hookup:"Full hookups, 20/30/50 amp", phone:"(346) 375-4316", web:"cutnshootrvpark.com", tags:["Small park","Pull-through sites","Short or long-term stays"] },
  { name:"St. Ives RV Resort", address:"4959 FM 2917, Alvin, TX 77511", year:"", city:"Alvin", county:"Brazoria", state:"Texas", region:"Houston Metro TX", type:"Private", sites:72, hookup:"Full hookup sites, pull-through and back-in", phone:"(832) 838-4204", web:"stivesrvresort.com", tags:["Harvest Hosts network","Weekly activities","Big rig friendly"] },
  { name:"Peaceful Pines RV Park", address:"16981 Old Houston Rd, Conroe, TX 77302", year:"", city:"Conroe", county:"Montgomery", state:"Texas", region:"Houston Metro TX", type:"Private", sites:18, hookup:"Full hookups, electric 30/50 amp, water", phone:"(936) 310-3692", web:"peacefulpinesrv-tx.com", tags:["Small quiet park","Wooded/pine setting","Pet friendly","Free WiFi"] },

  { name:"Post Oak Place RV Park", address:"109 Massey St, Denton, TX 76205", year:"", city:"Denton", county:"Denton", state:"Texas", region:"North TX", type:"Private", sites:95, hookup:"Full hookups, 30/50 amp, level concrete pads", phone:"(940) 387-8584", web:"postoakplace.com", tags:["100-year-old post oak trees","Shaded sites"] },
  { name:"Sundowner RV Park", address:"11595 CR 439, Princeton, TX 75407", year:"", city:"Princeton", county:"Collin", state:"Texas", region:"North TX", type:"Private", sites:95, hookup:"Full hookups, sub-metered electric, water, sewer", phone:"(214) 449-1533", web:"sundownerrvpark.com", tags:["Covered sites","Concrete patios","Monthly rates"] },
  { name:"Hidden Acres RV Park", address:"10364 County Rd 740, Princeton, TX 75407", year:"", city:"Princeton", county:"Collin", state:"Texas", region:"North TX", type:"Private", sites:38, hookup:"Full hookups, 20/30/50 amp, water, sewer", phone:"(972) 736-1264", web:"hiddenacresrv.com", tags:["Lake Lavon beach access","High-speed internet included"] },

  { name:"Cardinal RV Park", address:"2575 W Cardinal Dr, Beaumont, TX 77705", year:"", city:"Beaumont", county:"Jefferson", state:"Texas", region:"Golden Triangle TX", type:"Private", sites:60, hookup:"Full hookups, paved back-in and pull-thru sites", phone:"(409) 554-0156", web:"cardinalrvparks.com", tags:["Paved sites","Pull-thru & back-in","Dog park","Near US-96"] },
  { name:"Pleasure Island RV Park", address:"540 S Spoil Levee Rd, Port Arthur, TX 77640", year:"", city:"Port Arthur", county:"Jefferson", state:"Texas", region:"Golden Triangle TX", type:"Private", sites:46, hookup:"Full hookups, level concrete pads", phone:"(409) 651-4171", web:"pleasureislandtx.com", tags:["Sabine Lake waterfront","Concrete pads","Nature trail","Bike path"] },
  { name:"Blue Elbow RV Park", address:"5573 Turner Rd, Orange, TX 77630", year:"", city:"Orange", county:"Orange", state:"Texas", region:"Golden Triangle TX", type:"Private", sites:10, hookup:"Full hookups: water, electric & sewer, 30/50 amp", phone:"(409) 330-1920", web:"blueelbow.com", tags:["Small park","Long pull-through sites","Monthly rates"] },
  { name:"East Lucas RV Park", address:"2590 E Lucas Dr, Beaumont, TX 77703", year:"", city:"Beaumont", county:"Jefferson", state:"Texas", region:"Golden Triangle TX", type:"Private", sites:50, hookup:"47 full hookup sites plus 3 electric/water sites; pull-thru and back-in", phone:"(409) 899-9209", web:"eastlucasrvpark.webflow.io", tags:["Long-term stays","Fiber WiFi","Pull-thru & back-in"] },
  { name:"Access RV Park", address:"2565 95th St, Port Arthur, TX 77640", year:"", city:"Port Arthur", county:"Jefferson", state:"Texas", region:"Golden Triangle TX", type:"Private", sites:85, hookup:"Full hookups, 30/50 amp, concrete driveways and pads", phone:"(409) 729-8000", web:"accessrvpark.com", tags:["Concrete pads","Cabin rentals","Long-term sites"] },

  { name:"Vaquero Village R.V. Park", address:"16594 U.S. Highway 83 N, Laredo, TX 78045", year:"", city:"Laredo", county:"Webb", state:"Texas", region:"South TX", type:"Private", sites:78, hookup:"Full hookups, 30/50 amp, concrete pads, back-in/pull-through", phone:"(956) 417-4141", web:"", tags:["Highway 83","Concrete pads","Pet-friendly","Border-area"] },
  { name:"Towne North Mobile Home & RV Park", address:"301 International Blvd, Laredo, TX 78045", year:"", city:"Laredo", county:"Webb", state:"Texas", region:"South TX", type:"Private", sites:40, hookup:"Full hookups, electric, water, 30/50 amp, dump station", phone:"(956) 727-1222", web:"hometowncommunities.com", tags:["Mobile home community","Laundry facilities","Dump station"] },
  { name:"San Ygnacio RV Park", address:"4347 N US Highway 83, San Ygnacio, TX 78067", year:"", city:"San Ygnacio", county:"Zapata", state:"Texas", region:"South TX", type:"Private", sites:72, hookup:"Full hookups, 30/50 amp, fiber WiFi", phone:"(956) 307-8535", web:"sytrvpark.com", tags:["Near Falcon Lake","Boat ramp","Fishing","EV charger"] },
  { name:"Amigo Inn & RV Park", address:"209 Lake Shore Dr, Zapata, TX 78076", year:"", city:"Zapata", county:"Zapata", state:"Texas", region:"South TX", type:"Private", sites:65, hookup:"Full hookups (water, sewer, electric), 30/50 amp, cable TV, WiFi", phone:"(956) 765-3095", web:"amigoinn-rvpark.com", tags:["Near Falcon Lake","Laundry facilities","Hot showers"] },
  { name:"Lucky Eagle RV Park", address:"794 Lucky Eagle Drive, Eagle Pass, TX 78852", year:"", city:"Eagle Pass", county:"Maverick", state:"Texas", region:"South TX", type:"Private", sites:20, hookup:"Full hookups, 50 amp, back-in sites", phone:"(888) 255-8259", web:"luckyeagletexas.com", tags:["Casino resort","Back-in sites","Near Rio Grande"] },

  { name:"Mission Trails RV Resort", address:"3500 Orkney, San Antonio, TX 78223", year:"", city:"San Antonio", county:"Bexar", state:"Texas", region:"South TX", type:"Private", sites:70, hookup:"Full hookups", phone:"(210) 928-8285", web:"missiontrailsrv.com", tags:["Near downtown","Public transit access"] },
  { name:"River Shade RV Park", address:"3995 S Hwy 123 Bypass, Seguin, TX 78155", year:"", city:"Seguin", county:"Guadalupe", state:"Texas", region:"South TX", type:"Private", sites:85, hookup:"Full hookups, side yards, big rig friendly", phone:"(830) 379-8826", web:"rivershadervpark.net", tags:["Guadalupe River area","WiFi and cable"] },
  { name:"Rustic Waters RV Resort", address:"7327 Elm Creek Rd, Seguin, TX 78155", year:"", city:"Seguin", county:"Guadalupe", state:"Texas", region:"South TX", type:"Private", sites:81, hookup:"Full hookups, 50/30/20 amp, concrete patios", phone:"(830) 730-8591", web:"rusticwatersrvresort.com", tags:["Swimming pond","Petting zoo","Fire pits"] },
  { name:"Seguin Hilltop RV Resort", address:"4000 W I-10 Frontage Rd, Seguin, TX 78155", year:"", city:"Seguin", county:"Guadalupe", state:"Texas", region:"South TX", type:"Private", sites:25, hookup:"Full hookups, 30/50 amp, pull-thru sites", phone:"(830) 379-9998", web:"seguinhilltoprv.com", tags:["I-10 access","Small park"] },
  { name:"Alamo River RV Park & Campground", address:"12430 Trawalter Ln, Von Ormy, TX 78073", year:"", city:"Von Ormy", county:"Bexar", state:"Texas", region:"South TX", type:"Private", sites:50, hookup:"Full hookups, 50 amp electric, water, sewer", phone:"(210) 622-5022", web:"", tags:["Medina River access","Fishing","Recently renovated"] },

  { name:"Twin Pine RV Park", address:"1202 US Hwy 84, Slaton, TX 79364", year:"", city:"Slaton", county:"Lubbock", state:"Texas", region:"Panhandle TX", type:"Private", sites:72, hookup:"Full hookups, 20/30/50 amp electric, water, sewer", phone:"(806) 828-3311", web:"twinpinervpark.com", tags:["Historic Slaton","Pet run","Laundry & kitchen"] },
  { name:"Buggies RV Park", address:"1102 Seagraves Rd, Brownfield, TX 79316", year:"", city:"Brownfield", county:"Terry", state:"Texas", region:"Panhandle TX", type:"Private", sites:30, hookup:"Full hookups", phone:"(806) 777-2109", web:"buggiesrv.com", tags:["South Plains","Full hookups"] },
  { name:"Panhandle Lodging RV Park", address:"24501 Hix Dr, Canyon, TX 79015", year:"", city:"Canyon", county:"Randall", state:"Texas", region:"Panhandle TX", type:"Private", sites:41, hookup:"Full hookups, 30/50 amp, water, sewer", phone:"(806) 680-3401", web:"panhandlelodging.com", tags:["Near West Texas A&M","Near Palo Duro Canyon","Laundry & WiFi"] },
  { name:"The Silos at Canyon RV Park", address:"19671 City Lake Road, Canyon, TX 79015", year:"", city:"Canyon", county:"Randall", state:"Texas", region:"Panhandle TX", type:"Private", sites:12, hookup:"Full hookups, 20/30/50 amp electric, water, sewer", phone:"(806) 433-7251", web:"thesilosrvpark.com", tags:["Pull-thrus to 70 ft","Near Palo Duro Canyon"] },
  { name:"Urban Hidden Acres RV Park", address:"1708 W Kentucky, Pampa, TX 79065", year:"", city:"Pampa", county:"Gray", state:"Texas", region:"Panhandle TX", type:"Private", sites:25, hookup:"Full hookups, 30/50 amp, water, sewer, concrete patios", phone:"(806) 665-6217", web:"urbanhiddenacresrv.com", tags:["Storm shelter access","Near Clarendon College"] },
  { name:"Ken's RV Park", address:"9003 Hwy 136, Borger, TX 79007", year:"", city:"Borger", county:"Hutchinson", state:"Texas", region:"Panhandle TX", type:"Private", sites:14, hookup:"Full hookups, 20/30/50 amp, water, sewer", phone:"(806) 865-3877", web:"", tags:["Full hookups","West of Borger"] },
  { name:"Yerby's RV Park", address:"1521 S Meredith Ave, Dumas, TX 79029", year:"", city:"Dumas", county:"Moore", state:"Texas", region:"Panhandle TX", type:"Private", sites:52, hookup:"Full hookups, 50 amp electric, water, sewer", phone:"(806) 935-4940", web:"yerbysrvpark.com", tags:["Family owned since 1985","Laundry facility"] },
  { name:"Scenic Valley RV Park", address:"14100 S Western St, Amarillo, TX 79118", year:"", city:"Amarillo", county:"Randall", state:"Texas", region:"Panhandle TX", type:"Private", sites:20, hookup:"Full hookups, 30/50 amp", phone:"(806) 433-7469", web:"scenicvalleyrvpark.com", tags:["Privacy fences","Near Palo Duro Canyon"] },
  { name:"Windmill Ranch RV Park & Cabins", address:"800 N Hale Ave, Tulia, TX 79088", year:"", city:"Tulia", county:"Swisher", state:"Texas", region:"Panhandle TX", type:"Private", sites:15, hookup:"Full hookups, 20/30/50 amp, water, sewer", phone:"", web:"windmillranchtulia.com", tags:["Midway Lubbock-Amarillo on I-27","Cabins on-site"] },

  { name:"Trailmarker RV Park", address:"4610 FM 1327, Buda, TX 78610", year:"", city:"Buda", county:"Hays", state:"Texas", region:"Austin Area TX", type:"Private", sites:71, hookup:"Full hookups, 20/30/50 amp electric, water, sewer, dump station", phone:"(737) 414-3533", web:"trailmarkertx.com", tags:["Near I-35 & SH 130","Pool","Pet-friendly"] },
  { name:"Canyon Trail RV Park", address:"6050 S Interstate 35 Frontage Rd, San Marcos, TX 78666", year:"", city:"San Marcos", county:"Hays", state:"Texas", region:"Austin Area TX", type:"Private", sites:89, hookup:"Full hookups, 30/50 amp, concrete pads, pull-through sites", phone:"(512) 805-9988", web:"canyontrailrv.com", tags:["Long-term & seasonal stays","I-35 frontage","Big-rig friendly"] },
  { name:"Crazy Horse Estate RV Park", address:"70 Iron Horse Dr, Hutto, TX 78634", year:"", city:"Hutto", county:"Williamson", state:"Texas", region:"Austin Area TX", type:"Private", sites:26, hookup:"Full hookups, 20/30/50 amp at each space", phone:"(512) 310-8063", web:"crazyhorseestatervpark.com", tags:["Long-term RV living","Pull-through sites","Small community"] },
  { name:"Big Oaks RV Park and Storage", address:"3330 W Whitestone Blvd, Cedar Park, TX 78613", year:"", city:"Cedar Park", county:"Williamson", state:"Texas", region:"Austin Area TX", type:"Private", sites:96, hookup:"Full hookups, 20/30/50 amp electric, water, sewer", phone:"(512) 267-1775", web:"bigoaksrvpark.com", tags:["On-site RV storage","Gated dog parks","Mostly long-term residents"] },
  { name:"Meadow Lane RV Park", address:"16201 Summit Dr, Austin, TX 78728", year:"", city:"Austin", county:"Travis", state:"Texas", region:"Austin Area TX", type:"Private", sites:56, hookup:"Full hookups, 30/50 amp", phone:"(512) 887-8901", web:"meadowlanerv.com", tags:["Near Pflugerville","North Austin","Full hookups"] },
  { name:"The View RV Park", address:"3305 Goforth Rd, Kyle, TX 78640", year:"", city:"Kyle", county:"Hays", state:"Texas", region:"Austin Area TX", type:"Private", sites:6, hookup:"Full hookups, 30/50 amp and water at every site", phone:"(512) 626-6827", web:"theviewrvparkkyle.com", tags:["Private lake","Small intimate park","Hill Country views"] },

  { name:"Hidden Cove RV Park & Marina", address:"20400 Hackberry Creek Park Rd, Frisco, TX 75036", year:"", city:"Frisco", county:"Denton", state:"Texas", region:"North TX", type:"Private", sites:88, hookup:"Full hookups (46 sites) plus water/electric sites, 30/50 amp, paved back-in pads", phone:"(972) 294-1443", web:"hiddencovepark.net", tags:["Lake Lewisville","Marina","Boat ramp","Fire rings"] },
  { name:"Easy Lane RV Park", address:"8888 Easy Ln, McKinney, TX 75071", year:"", city:"McKinney", county:"Collin", state:"Texas", region:"North TX", type:"Private", sites:18, hookup:"Full hookups, 30/50 amp, water, sewer, dual 110 outlets", phone:"(469) 688-8664", web:"easylanervpark.com", tags:["Clubhouse","Dog park","Historic barn on site"] },
  { name:"Dallas Wylie RV Park", address:"1805 E Stone Rd, Wylie, TX 75098", year:"", city:"Wylie", county:"Collin", state:"Texas", region:"North TX", type:"Private", sites:51, hookup:"Full hookups, 20/30/50 amp, pull-through and back-in", phone:"(972) 772-1372", web:"rvparkwylie.com", tags:["Gated premium lots","Pet friendly","Long-term stays"] },
  { name:"Dallas Rockwall RV Park", address:"2220 Troy Rd, Wylie, TX 75098", year:"", city:"Wylie", county:"Collin", state:"Texas", region:"North TX", type:"Private", sites:31, hookup:"Full hookups, 30/50 amp, pull-through sites, dump station", phone:"(214) 296-9096", web:"rvparkdfw.com", tags:["Shaded sites","On-site security","Long-term stays"] },
  { name:"Holiday Village RV Park", address:"6610 S State Hwy 78, Sachse, TX 75048", year:"", city:"Sachse", county:"Dallas", state:"Texas", region:"North TX", type:"Private", sites:16, hookup:"Full hookups", phone:"(214) 473-5961", web:"hv-rvpark.com", tags:["Near Lake Ray Hubbard","Small park","Year-round"] },
  { name:"Plantation Place RV Park", address:"345 Barnes Bridge Rd, Sunnyvale, TX 75182", year:"", city:"Sunnyvale", county:"Dallas", state:"Texas", region:"North TX", type:"Private", sites:60, hookup:"Full hookups, 20/30/50 amp, pull-through, cable TV", phone:"(469) 846-9839", web:"plantationplacerv.com", tags:["Private 5-acre lake","24-hour security","Pull-through sites"] },

  { name:"Marshall Meadows RV & Tiny Home Village", address:"2226 Blocker Road, Marshall, TX 75672", year:"", city:"Marshall", county:"Harrison", state:"Texas", region:"East TX", type:"Private", sites:38, hookup:"Full hookups", phone:"(903) 303-2268", web:"marshallmeadowsrvpark.com", tags:["Private fishing pond","Tiny homes on-site","Extended stay"] },
  { name:"Forest Country RV Park", address:"5001 US Highway 59 N, Nacogdoches, TX 75964", year:"", city:"Nacogdoches", county:"Nacogdoches", state:"Texas", region:"East TX", type:"Private", sites:50, hookup:"Full hookups, 50 amp", phone:"(936) 559-1645", web:"forestcountryrvparktx.com", tags:["Pool","Pet-friendly"] },
  { name:"Nacogdoches RV Park", address:"3915 NW Stallings Dr, Nacogdoches, TX 75964", year:"", city:"Nacogdoches", county:"Nacogdoches", state:"Texas", region:"East TX", type:"Private", sites:15, hookup:"Full hookups, 30/50 amp", phone:"", web:"", tags:["RV storage on-site","Small park"] },
  { name:"Ford Chapel RV Park", address:"4220 FM 841, Lufkin, TX 75901", year:"", city:"Lufkin", county:"Angelina", state:"Texas", region:"East TX", type:"Private", sites:40, hookup:"Full hookups, 30/50 amp", phone:"(936) 632-7096", web:"lufkinrv.com", tags:["12-acre park","Security cameras"] },
  { name:"Good Life RV Park", address:"8747 US Highway 59, Burke, TX 75941", year:"", city:"Burke", county:"Angelina", state:"Texas", region:"East TX", type:"Private", sites:50, hookup:"Full hookups, 30/50 amp", phone:"(936) 526-2123", web:"thegoodlifervpark.com", tags:["Fishing pond","Pull-through sites","Near Lufkin"] },

  // ──────────────────────────────────────────────────────────
  //  TEXAS — LARGE PARKS, 100+ sites  (52 parks)
  //  Bigger resorts we track for reference — outside the site's
  //  usual small-park focus, shown under each state's "100+" tab.
  // ──────────────────────────────────────────────────────────

  { name:"DFW Mid-Cities RV Park", address:"4620 Kennedale New Hope Road, Fort Worth, TX 76140", year:"", city:"Fort Worth", county:"Tarrant", state:"Texas", region:"North TX", type:"Private", sites:103, hookup:"Full hookups, covered and premium sites", phone:"(817) 550-2202", web:"midcitiesrvpark.com", tags:["Long-term stays","Covered sites","Dog park","Fiber internet"] },
  { name:"Yellow Rose RV Resort", address:"14445 White Settlement Rd, Fort Worth, TX 76108", year:"", city:"Fort Worth", county:"Parker", state:"Texas", region:"North TX", type:"Private", sites:147, hookup:"Full hookups, extra-wide back-in sites", phone:"(817) 229-8665", web:"yellowroservresort.com", tags:["21+ adult park","Pool","Dog parks","Big rig friendly"] },
  { name:"Highland Hideaway RV Resort", address:"1008 Highland Rd, Cleburne, TX 76033", year:"", city:"Cleburne", county:"Johnson", state:"Texas", region:"North TX", type:"Private", sites:108, hookup:"Full hookups, big rig friendly", phone:"(682) 916-3387", web:"highlandhideawayrvresort.com", tags:["Pool","Fitness center","Near downtown Cleburne"] },
  { name:"Northlake Village RV Park", address:"13001 Cleveland Gibbs Rd, Roanoke, TX 76262", year:"", city:"Roanoke", county:"Denton", state:"Texas", region:"North TX", type:"Private", sites:177, hookup:"Full hookups", phone:"(817) 430-3303", web:"northlakevillagerv.com", tags:["Near Texas Motor Speedway","DFW area","Long-term stays"] },
  { name:"Big Bend Station RV Park", address:"53623 TX-118, Terlingua, TX 79852", year:"", city:"Terlingua", county:"Brewster", state:"Texas", region:"Big Bend TX", type:"Private", sites:131, hookup:"Full hookups", phone:"(844) 637-0883", web:"bigbendstation.com", tags:["Near Big Bend National Park","Inn & RV combo","Restaurant on-site"] },
  { name:"Ransom Road RV Park", address:"240 Ransom Road, Aransas Pass, TX 78336", year:"", city:"Aransas Pass", county:"San Patricio", state:"Texas", region:"Coastal Bend TX", type:"Private", sites:128, hookup:"Full hookups", phone:"(361) 758-2715", web:"ransomroadrvparkinc.com", tags:["Intracoastal Waterway area","Gulf Coast fishing"] },
  { name:"Seven Oaks Resort", address:"801 South Inspiration Road, Mission, TX 78572", year:"", city:"Mission", county:"Hidalgo", state:"Texas", region:"Rio Grande Valley TX", type:"Private", sites:232, hookup:"Full hookups", phone:"(956) 581-0068", web:"sevenoaksresort.com", tags:["55+ resort","Pool & spa","Winter Texan destination"] },
  { name:"Paradise South RV Resort", address:"9099 N Mile 2 West Rd, Mercedes, TX 78570", year:"", city:"Mercedes", county:"Hidalgo", state:"Texas", region:"Rio Grande Valley TX", type:"Private", sites:493, hookup:"Full hookups", phone:"(956) 565-2044", web:"thousandtrails.com", tags:["55+ resort","Encore/Thousand Trails network","Winter Texan destination"] },

  { name:"Colonia del Rey RV Park", address:"1717 Waldron Rd, Corpus Christi, TX 78418", year:"", city:"Corpus Christi", county:"Nueces", state:"Texas", region:"Coastal Bend TX", type:"Private", sites:210, hookup:"Full hookups, 30/50 amp, concrete pads up to 80 ft", phone:"(361) 937-2435", web:"cdrrvpark.com", tags:["Flour Bluff","Family-owned since 1973","Outdoor pool","Dog park"] },
  { name:"Sunset Ridge RV Resort", address:"302 Graham Rd, Corpus Christi, TX 78418", year:"", city:"Corpus Christi", county:"Nueces", state:"Texas", region:"Coastal Bend TX", type:"Private", sites:158, hookup:"Full hookups, 30/50 amp, paved oversized sites", phone:"(361) 472-0072", web:"sunsetridgervresort.com", tags:["Flour Bluff","Paved sites","Oversized sites","Near Whitecap Beach"] },
  { name:"Sea Breeze RV Resort", address:"1026 Sea Breeze Ln, Portland, TX 78374", year:"", city:"Portland", county:"San Patricio", state:"Texas", region:"Coastal Bend TX", type:"Private", sites:142, hookup:"140 full hookups, 30/50 amp, 34 pull-through sites", phone:"(361) 643-0744", web:"seabreezerv.com", tags:["Nueces Bay views","Fishing pier","Pool","Big rig friendly"] },

  { name:"Mission RV Park", address:"1420 RV Dr, El Paso, TX 79928", year:"", city:"El Paso", county:"El Paso", state:"Texas", region:"El Paso TX", type:"Private", sites:188, hookup:"Full hookups, 30/50 amp electric, paved roads", phone:"(915) 859-1133", web:"missionrvparklp.com", tags:["Rock-wall enclosed","24-hr courtesy patrol","Big rig sites"] },

  { name:"Lucky's RV Park", address:"111 Hart Rd, Temple, TX 76501", year:"", city:"Temple", county:"Bell", state:"Texas", region:"Central TX", type:"Private", sites:101, hookup:"Full hookups, 20/30/50 amp electric, water, sewer", phone:"(254) 742-0711", web:"luckysrvtemple.com", tags:["Daily, weekly, monthly stays","Onsite propane","Near I-35"] },
  { name:"Itasca Creek RV Park", address:"5768 FM 67, Itasca, TX 76055", year:"", city:"Itasca", county:"Hill", state:"Texas", region:"Central TX", type:"Private", sites:100, hookup:"Full hookups, concrete pads", phone:"(254) 266-2344", web:"itascarvpark.com", tags:["Creekside walking trail","Pool","Near I-35"] },

  { name:"Tejas Valley RV Park & Campground", address:"13080 FM 1957, San Antonio, TX 78253", year:"", city:"San Antonio", county:"Bexar", state:"Texas", region:"South TX", type:"Private", sites:104, hookup:"Full hookups, 20/30/50 amp electric, water, sewer", phone:"(210) 679-7715", web:"tejasvalleyrvpark.com", tags:["Swimming pool","Game room","Dog park","Clubhouse"] },
  { name:"Texas 281 RV Park", address:"33300 US Hwy 281 N, Bulverde, TX 78163", year:"", city:"Bulverde", county:"Comal", state:"Texas", region:"South TX", type:"Private", sites:155, hookup:"Full hookups, 30/50 amp electric, water, sewer, paved pull-thrus", phone:"(830) 980-2282", web:"texas281rvpark.com", tags:["Big rig friendly","Pull-through sites","Hill Country"] },
  { name:"Greenlake RV Resort", address:"10842 Green Lake Street, San Antonio, TX 78223", year:"", city:"San Antonio", county:"Bexar", state:"Texas", region:"South TX", type:"Private", sites:236, hookup:"Full hookups, 30/50 amp electric, concrete pads", phone:"(210) 467-9178", web:"qualityrvresorts.com", tags:["Gated resort","Swimming pool","Long-term stays"] },

  { name:"Houston West RV Park", address:"35303 Cooper Rd, Brookshire, TX 77423", year:"", city:"Brookshire", county:"Waller", state:"Texas", region:"Houston Metro TX", type:"Private", sites:200, hookup:"Full hookups, water/sewer/electric, 30 & 50 amp", phone:"(281) 375-5678", web:"hwrvpark.com", tags:["I-10 corridor","Family-owned","24/7 onsite host","Big rig friendly"] },
  { name:"Summer Breeze USA RV Resort - Katy", address:"1019 Wilpitz Rd, Brookshire, TX 77423", year:"", city:"Brookshire", county:"Waller", state:"Texas", region:"Houston Metro TX", type:"Private", sites:100, hookup:"Full hookups, concrete sites, 30/50/100 amp electric", phone:"(713) 358-8430", web:"summerbreezeusa.com", tags:["Water park & splash pad","Good Sam 10/10 rated","Fitness center","Katy/I-10 area"] },
  { name:"Lakeview RV Resort", address:"11991 South Main St, Houston, TX 77035", year:"", city:"Houston", county:"Harris", state:"Texas", region:"Houston Metro TX", type:"Private", sites:100, hookup:"Full hookups, concrete pads, 30/50 amp", phone:"(713) 723-0973", web:"qualityrvresorts.com", tags:["Lakefront sites","Medical Center shuttle","Gated community","Pull-through & back-in"] },
  { name:"Wildwood Lakes RV Park", address:"500 FM 1942, Crosby, TX 77532", year:"", city:"Crosby", county:"Harris", state:"Texas", region:"Houston Metro TX", type:"Private", sites:200, hookup:"Full hookup RV sites", phone:"(281) 328-1155", web:"wildwoodlakesrv.com", tags:["Two private lakes","41-acre property","East Houston area","Cabin rentals"] },
  { name:"Galveston Bay RV Resort", address:"2000 Tri City Beach Rd, Baytown, TX 77523", year:"", city:"Baytown", county:"Chambers", state:"Texas", region:"Houston Metro TX", type:"Private", sites:133, hookup:"Full hookups, water, electric", phone:"(281) 420-3200", web:"galvestonbayresorttx.com", tags:["Waterfront on Galveston Bay","Off I-10","Condo rentals","Long-term friendly"] },
  { name:"Houston East RV Resort", address:"11810 I-10 E, Baytown, TX 77523", year:"", city:"Baytown", county:"Chambers", state:"Texas", region:"Houston Metro TX", type:"Private", sites:141, hookup:"Full hookups", phone:"(281) 383-3618", web:"houstoneastrvresort.com", tags:["I-10 corridor","East side of Houston","Rental units available"] },
  { name:"Jetstream RV Resort at Pearland", address:"2850 S Sam Houston Pkwy E, Houston, TX 77047", year:"", city:"Houston", county:"Harris", state:"Texas", region:"Houston Metro TX", type:"Private", sites:235, hookup:"Full hookups, 30 & 50 amp, concrete pads", phone:"(713) 433-6950", web:"jetstreamrvresortpearland.com", tags:["Near NRG Stadium","Fitness center & dog park","12 miles from Downtown Houston","Pool"] },
  { name:"Space Center RV Park", address:"301 Gulf Freeway South, League City, TX 77573", year:"", city:"League City", county:"Galveston", state:"Texas", region:"Houston Metro TX", type:"Private", sites:125, hookup:"Full hookups, water, electric, sewer, cable", phone:"(281) 554-8800", web:"spacervhouston.com", tags:["Near NASA Johnson Space Center","RV-only park","Free WiFi"] },
  { name:"Alvin RV Resort", address:"726 Nelson Rd, Alvin, TX 77511", year:"", city:"Alvin", county:"Brazoria", state:"Texas", region:"Houston Metro TX", type:"Private", sites:165, hookup:"Full hookups, 20/30/50 amp, water, sewer, high-speed internet", phone:"(713) 401-3135", web:"alvinrvresort.com", tags:["New RV community","Winter Texan friendly","40 min to Galveston or Downtown Houston"] },
  { name:"USA RV Resorts North Houston", address:"2150 Millstone Dr, Houston, TX 77073", year:"", city:"Houston", county:"Harris", state:"Texas", region:"Houston Metro TX", type:"Private", sites:255, hookup:"Full hookups, water, trash, WiFi included", phone:"(346) 646-7979", web:"usarvresorts.com", tags:["Two pools & hot tub","Near IAH airport","Cypress Creek trail access","Newer construction"] },
  { name:"USA RV Park", address:"20825 Southwest Freeway, Sugar Land, TX 77479", year:"", city:"Sugar Land", county:"Fort Bend", state:"Texas", region:"Houston Metro TX", type:"Private", sites:126, hookup:"Full hookups, 30/50 amp electric, water", phone:"(281) 343-0262", web:"", tags:["Southwest Freeway access","Big rig friendly (45ft max)","Laundromat on site"] },

  { name:"Traders Village RV Park & Camp Ground", address:"2602 Mayfield Rd, Grand Prairie, TX 75052", year:"", city:"Grand Prairie", county:"Tarrant", state:"Texas", region:"North TX", type:"Private", sites:239, hookup:"Full hookups, 30/50 amp, water & sewer", phone:"(972) 647-8205", web:"tradersvillage.com", tags:["Flea market on-site","Pool","Pull-through sites"] },
  { name:"Sandy Lake RV & MH Resort", address:"1915 Sandy Lake Rd, Carrollton, TX 75006", year:"", city:"Carrollton", county:"Dallas", state:"Texas", region:"North TX", type:"Private", sites:219, hookup:"Full hookups, 30/50 amp, water, sewer", phone:"(972) 242-6808", web:"sunoutdoors.com/texas/sandy-lake-rv-community", tags:["Near Sandy Lake Amusement Park","Fitness center","Dog park"] },
  { name:"Northside RV Resort", address:"200 E Butcher Rd, Waxahachie, TX 75165", year:"", city:"Waxahachie", county:"Ellis", state:"Texas", region:"North TX", type:"Private", sites:230, hookup:"Full hookups, 30/50 amp, concrete pads", phone:"(972) 908-0040", web:"northsidervresort.com", tags:["Private fishing lake","Swimming pool","Near I-35"] },
  { name:"Treetops RV Resort", address:"1901 W Arbrook Blvd, Arlington, TX 76015", year:"", city:"Arlington", county:"Tarrant", state:"Texas", region:"North TX", type:"Private", sites:169, hookup:"Full hookups, 30/50 amp, concrete patios", phone:"(817) 467-7943", web:"sunoutdoors.com/texas/treetops-rv-community", tags:["Concrete patios","Shade trees","Cable TV"] },
  { name:"Flying Dutchman RV Resort", address:"2356 FM 66, Waxahachie, TX 75167", year:"", city:"Waxahachie", county:"Ellis", state:"Texas", region:"North TX", type:"Private", sites:113, hookup:"Full hookups, 30/50 amp, paved parking", phone:"(214) 949-0310", web:"flyingdutchmanrvresort.com", tags:["Gated entry","Big-rig friendly","Paved sites"] },
  { name:"Wagon Master RV Park & Alpaca Farm", address:"3926 FM 455 W, Sanger, TX 76266", year:"", city:"Sanger", county:"Denton", state:"Texas", region:"North TX", type:"Private", sites:102, hookup:"Full hookups, 20/30/50 amp, water & sewer", phone:"(940) 500-8973", web:"wagonmasterrv.com", tags:["Alpaca farm on-site","Pool","North of Denton"] },

  { name:"Golden Triangle RV Resort", address:"5760 W Port Arthur Rd, Port Arthur, TX 77640", year:"", city:"Port Arthur", county:"Jefferson", state:"Texas", region:"Golden Triangle TX", type:"Private", sites:137, hookup:"Full 30/50 amp hookups, water, and sewer; concrete pads", phone:"(409) 299-8208", web:"goldentrianglervresort.com", tags:["Concrete pads","Pool & hot tub","Fitness center","Clubhouse"] },
  { name:"Orange Texas RV Resort", address:"18017 Hwy 62 S, Orange, TX 77630", year:"", city:"Orange", county:"Orange", state:"Texas", region:"Golden Triangle TX", type:"Private", sites:194, hookup:"Full hookups, 30/50 amp service, 30x60 concrete lots", phone:"(409) 883-3400", web:"orangetxrvresort.com", tags:["Large concrete lots","30/50 amp","Near I-10"] },
  { name:"Grand Pines of Texas RV Resort", address:"18179 I-10, Beaumont, TX 77705", year:"", city:"Beaumont", county:"Jefferson", state:"Texas", region:"Golden Triangle TX", type:"Private", sites:100, hookup:"Full hookups, concrete pads", phone:"(409) 333-0322", web:"grandpinesrvresort.com", tags:["Fishing lagoon","Pool","Dog park","Nature trail"] },

  { name:"Stone Creek RV Park", address:"18905 IH 35 N, Schertz, TX 78154", year:"", city:"Schertz", county:"Guadalupe", state:"Texas", region:"South TX", type:"Private", sites:324, hookup:"Full hookups, 30/50 amp electric, some covered patios, pull-thru sites", phone:"(830) 609-7759", web:"stonecreekrvpark.com", tags:["Big rig friendly","Pool","I-35 access"] },
  { name:"Mission City RV Park", address:"1011 Gembler Rd, San Antonio, TX 78219", year:"", city:"San Antonio", county:"Bexar", state:"Texas", region:"South TX", type:"Private", sites:162, hookup:"Full hookups, 30/50 amp, back-in and pull-thru", phone:"(210) 337-6501", web:"", tags:["Pool","Near downtown San Antonio","Pet friendly"] },
  { name:"Treeside RV Resort", address:"8989 N Interstate 35 Frontage Rd, New Braunfels, TX 78130", year:"", city:"New Braunfels", county:"Comal", state:"Texas", region:"South TX", type:"Private", sites:260, hookup:"Full hookups, 20/30/50 amp, WiFi", phone:"(512) 781-7800", web:"treesiderv.com", tags:["45 acres","Cabins on site","Big rig friendly"] },
  { name:"Canopy RV Resort", address:"1160 Lakeside Pass, New Braunfels, TX 78130", year:"", city:"New Braunfels", county:"Comal", state:"Texas", region:"South TX", type:"Private", sites:290, hookup:"Full hookups, 30/50 amp, pull-thru up to 100 ft", phone:"(830) 310-8511", web:"canopyrvresort.com", tags:["Resort pool","Pickleball courts","Fiber WiFi"] },

  { name:"The Retreat RV Resort", address:"7516 I-27, Lubbock, TX 79404", year:"", city:"Lubbock", county:"Lubbock", state:"Texas", region:"Panhandle TX", type:"Private", sites:394, hookup:"Full hookups, 20/30/50 amp power, water, sewer; some covered sites", phone:"(806) 368-8613", web:"theretreatrvresort.com", tags:["Covered sites available","South Plains","Big rig friendly"] },
  { name:"Fort Amarillo RV Resort", address:"10101 Amarillo Blvd West, Amarillo, TX 79124", year:"", city:"Amarillo", county:"Potter", state:"Texas", region:"Panhandle TX", type:"Private", sites:105, hookup:"Full hookups, pull-thrus to 90 ft", phone:"(806) 331-1700", web:"fortrvparks.com", tags:["Historic Route 66","Indoor heated pool","Big rig friendly"] },

  { name:"Longhorn RV Resort & Storage", address:"12921 Camino Real, Niederwald, TX 78640", year:"", city:"Niederwald", county:"Hays", state:"Texas", region:"Austin Area TX", type:"Private", sites:196, hookup:"Full hookups, level concrete pads, 50-ft site spacing", phone:"(512) 200-9677", web:"longhornrvresort.com", tags:["60-acre private lake","Gated community","Registered longhorns on-site"] },
  { name:"San Marcos River Resort", address:"745 S Main St, Fentress, TX 78622", year:"", city:"Fentress", county:"Caldwell", state:"Texas", region:"Austin Area TX", type:"Private", sites:125, hookup:"Full hookups, 20/30/50 amp electric, water, sewer", phone:"(512) 213-0112", web:"sanmarcosriverresort.com", tags:["San Marcos River access","Pecan tree shade","Back-in & pull-thru sites"] },
  { name:"Redbud Ranch RV Resort", address:"211 Benelli Drive, Hutto, TX 78634", year:"", city:"Hutto", county:"Williamson", state:"Texas", region:"Austin Area TX", type:"Private", sites:147, hookup:"Full hookups, concrete pads", phone:"(512) 265-8000", web:"redbudrvresort.com", tags:["Back-in, pull-through & buddy sites","Cabin rentals on-site","Near Round Rock"] },
  { name:"Great Escapes RV Resort Elgin", address:"16740 Albert Voelker Rd, Elgin, TX 78621", year:"", city:"Elgin", county:"Bastrop", state:"Texas", region:"Austin Area TX", type:"Private", sites:238, hookup:"Full hookups, 20/30/50 amp electric, water, sewer", phone:"(512) 648-2800", web:"greatescapeselgin.com", tags:["Large resort","Pool & playground","Long-term & seasonal stays"] },

  { name:"Lakeshore RV Resort", address:"1233 E Interstate 30, Garland, TX 75043", year:"", city:"Garland", county:"Dallas", state:"Texas", region:"North TX", type:"Private", sites:192, hookup:"Full hookups, concrete streets and pads, electric/water/sewer/cable/WiFi", phone:"(469) 661-3827", web:"lakeshorervresort.com", tags:["Lake Ray Hubbard","Pool and hot tub","Pull-through and waterfront sites"] },
  { name:"Waterfront Hideaway Ranch", address:"640 Lloyds Rd, Little Elm, TX 75068", year:"", city:"Little Elm", county:"Denton", state:"Texas", region:"North TX", type:"Private", sites:100, hookup:"Full hookups, 30/50 amp, water, sewer", phone:"(972) 782-9722", web:"waterfronthideawayranch.com", tags:["Lake Lewisville","Private shoreline","Cabins on site"] },

  { name:"Fernbrook RV Park", address:"2073 FM 2011, Longview, TX 75603", year:"", city:"Longview", county:"Gregg", state:"Texas", region:"East TX", type:"Private", sites:128, hookup:"Full hookups, concrete pads, 30/50 amp", phone:"(903) 643-8888", web:"fernbrookpark.com", tags:["Big rig friendly","Pool","Clubhouse"] },
  { name:"Antique Capital RV Park", address:"500 S Loop 485, Gladewater, TX 75647", year:"", city:"Gladewater", county:"Gregg", state:"Texas", region:"East TX", type:"Private", sites:142, hookup:"Full hookups, concrete pads, 30/50 amp, cable TV", phone:"(903) 845-7378", web:"acrvpark.com", tags:["Fishing pond","Big rig friendly","Antiques town"] },
  { name:"Stillwater RV Resort", address:"11684 Barber Rd, Winona, TX 75792", year:"", city:"Winona", county:"Smith", state:"Texas", region:"East TX", type:"Private", sites:171, hookup:"Full hookups, concrete pads", phone:"(903) 483-4414", web:"stillwaterrvresort.com", tags:["Lazy river","Saltwater pools","Luxury resort","Off I-20"] },

  // ──────────────────────────────────────────────────────────
  //  ADD YOUR NEXT STATE HERE
  //  Example template (copy and fill in):
  // ──────────────────────────────────────────────────────────
  //
  // { name:"Park Name",
  //   address:"123 Main St, City, ST 12345",
  //   city:"City", county:"County", state:"Georgia",
  //   region:"North GA",
  //   type:"Private",
  //   sites:45,
  //   hookup:"Full hookups, 30/50A",
  //   phone:"(555) 123-4567",
  //   web:"parkwebsite.com",         // leave "" if no website
  //   tags:["Lake","Fishing","Quiet"]
  // },

];
