// ============================================================
//  data.js — RV Parks USA
//  HOW TO ADD A NEW STATE:
//  1. Copy one of the state objects below as a template
//  2. Change the "state" field on every park entry
//  3. Push your changes — the site rebuilds automatically
//
//  REQUIRED FIELDS PER PARK:
//    name, city, county, state, region, type, sites,
//    hookup, phone, web, tags, address
//
//  VALID TYPES: "Private"
//
//  HOOKUP KEYWORDS (used by filter):
//    "Full hookups" | "Electric" | "Water" | "No hookups"
// ============================================================

const PARKS = [

  // ──────────────────────────────────────────────────────────
  //  TENNESSEE  (27 parks)
  // ──────────────────────────────────────────────────────────

  { name:"Mountain Glen RV Park", address:"6182 Brockdell Rd, Greeneville, TN 37745", year:"", city:"Greeneville", county:"Greene", state:"Tennessee", region:"East TN", type:"Private", sites:45, hookup:"Full hookups, 50A, pull-throughs", phone:"(423) 234-0404", web:"mountainglenrv.com", tags:["Fishing pond","Pavilion","WiFi"] },
  { name:"Creekside RV Park", address:"2475 Henderson Springs Rd, Pigeon Forge, TN 37863", year:"", city:"Pigeon Forge", county:"Sevier", state:"Tennessee", region:"East TN", type:"Private", sites:42, hookup:"Full hookups (W/E/S), concrete pads", phone:"(865) 428-4801", web:"creeksidervpark.com", tags:["Little Pigeon River","Smokies"] },
  { name:"Up the Creek RV Camp", address:"1919 Little Valley Rd, Pigeon Forge, TN 37862", year:"", city:"Pigeon Forge", county:"Sevier", state:"Tennessee", region:"East TN", type:"Private", sites:60, hookup:"Full hookups, concrete pads, fire pits", phone:"(865) 453-8474", web:"upthecreekrvcamp.com", tags:["Smokies","Dollywood nearby"] },
  { name:"Mecca Camp Resort", address:"1301 Mecca Pike, Tellico Plains, TN 37385", year:"", city:"Tellico Plains", county:"Monroe", state:"Tennessee", region:"East TN", type:"Private", sites:50, hookup:"Full hookups, 30/50A", phone:"(423) 253-2266", web:"meccacampresort.com", tags:["Cherokee NF","Cherohala Skyway","Family events"] },
  { name:"Rivers Edge Campground", address:"4220 Huskey St, Pigeon Forge, TN 37863", year:"", city:"Pigeon Forge", county:"Sevier", state:"Tennessee", region:"East TN", type:"Private", sites:60, hookup:"Full hookups, riverside sites", phone:"(865) 453-5734", web:"riversedgepigeonforge.com", tags:["Pigeon River","Smokies","Dollywood"] },
  { name:"Camp LeConte Luxury Outdoor Resort", address:"1739 E Pkwy, Gatlinburg, TN 37738", year:"", city:"Gatlinburg", county:"Sevier", state:"Tennessee", region:"East TN", type:"Private", sites:55, hookup:"Full hookups, 30/50A, WiFi", phone:"(865) 436-6716", web:"campinggatlinburg.com", tags:["Gatlinburg","Pool","Hot tub","Smokies"] },
  { name:"Smoky Waters Campground", address:"346 Wears Valley Rd, Townsend, TN 37882", year:"", city:"Townsend", county:"Blount", state:"Tennessee", region:"East TN", type:"Private", sites:45, hookup:"Full hookups, pull-throughs", phone:"(865) 448-6421", web:"", tags:["Little River","Smokies gate","Quiet valley"] },
  { name:"Lakeview RV Resort", address:"4550 Hwy 11 E, Bluff City, TN 37618", year:"", city:"Bluff City", county:"Sullivan", state:"Tennessee", region:"East TN", type:"Private", sites:50, hookup:"Full hookups (W/E/S), WiFi, 30/50A", phone:"(423) 538-7090", web:"lakeviewrvresort.net", tags:["Boone Lake","Tri-Cities area","Year-round"] },
  { name:"Raccoon Mountain Campground", address:"319 W Hills Dr, Chattanooga, TN 37419", year:"", city:"Chattanooga", county:"Hamilton", state:"Tennessee", region:"East TN", type:"Private", sites:70, hookup:"Full hookups, gravel pads, 30/50A", phone:"(423) 821-9403", web:"raccoonmountain.com", tags:["Chattanooga","Caverns","Mountain views"] },
  { name:"Long Creek Haven", address:"1430 TN-340, Del Rio, TN 37727", year:"", city:"Newport", county:"Cocke", state:"Tennessee", region:"East TN", type:"Private", sites:20, hookup:"Full hookups, 30/50A, creek access", phone:"", web:"", tags:["Pigeon River tributary","Small park","Quiet"] },
  { name:"Bucks Ranch", address:"2193 Keazy Hollow Rd, Telford, TN 37690", year:"", city:"Telford", county:"Washington", state:"Tennessee", region:"East TN", type:"Private", sites:25, hookup:"Electric + water", phone:"", web:"", tags:["Rural East TN","Quiet","Small family park"] },
  { name:"Spring Lake RV Resort", address:"255 Fairview Dr, Spring City, TN 37381", year:"", city:"Spring City", county:"Rhea", state:"Tennessee", region:"East TN", type:"Private", sites:64, hookup:"Full hookups, 30/50A, WiFi, cable", phone:"(423) 365-6555", web:"", tags:["Watts Bar Lake","Monthly rates"] },
  { name:"Grand Ole RV Resort & Market", address:"708 N Main St, Goodlettsville, TN 37072", year:"", city:"Goodlettsville", county:"Davidson", state:"Tennessee", region:"Middle TN", type:"Private", sites:75, hookup:"Full hookups (W/E/S), gravel pads", phone:"(615) 851-4555", web:"grandolervresort.com", tags:["Nashville area","Live music","Restaurant"] },
  { name:"Two Rivers Campground", address:"2616 Music Valley Dr, Nashville, TN 37214", year:"", city:"Goodlettsville", county:"Davidson", state:"Tennessee", region:"Middle TN", type:"Private", sites:65, hookup:"Full hookups, WiFi", phone:"(615) 883-8559", web:"tworiverscampground.com", tags:["Nashville","Opryland area","Pool"] },
  { name:"RJourney Clarksville RV Resort", address:"1270 Tylertown Rd, Clarksville, TN 37040", year:"", city:"Clarksville", county:"Montgomery", state:"Tennessee", region:"Middle TN", type:"Private", sites:97, hookup:"Full hookups, pull-throughs, 30/50A", phone:"(931) 774-7901", web:"rjourney.com", tags:["Fort Campbell area","Nashville day trip"] },
  { name:"Piney River Resort", address:"6869 Piney River Rd N, Bon Aqua, TN 37025", year:"", city:"Dickson", county:"Dickson", state:"Tennessee", region:"Middle TN", type:"Private", sites:60, hookup:"Full hookups, concrete pads, riverfront sites", phone:"(931) 996-3431", web:"pineyriverresort.com", tags:["Piney River","Nashville day trip"] },
  { name:"Campers RV Park", address:"Spring Hill, TN 37174", year:"", city:"Spring Hill", county:"Maury", state:"Tennessee", region:"Middle TN", type:"Private", sites:50, hookup:"Full hookups, 30/50A", phone:"(615) 302-5775", web:"", tags:["Short-term & monthly","Nashville area"] },
  { name:"Country Life RV Parks and Services", address:"1204 Campground Rd, Clarkrange, TN 38553", year:"", city:"Clarkrange", county:"Fentress", state:"Tennessee", region:"Middle TN", type:"Private", sites:30, hookup:"Full hookups", phone:"(931) 863-3000", web:"", tags:["Rural","Monthly rates"] },
  { name:"Gracious Gardens RV Park", address:"Crossville, TN 38555", year:"", city:"Crossville", county:"Cumberland", state:"Tennessee", region:"Middle TN", type:"Private", sites:40, hookup:"Full hookups, 30/50A", phone:"(931) 707-7979", web:"", tags:["Cumberland Plateau","Monthly rates"] },
  { name:"Harmony Ridge RV Park", address:"2850 McGee Rd, Jamestown, TN 38556", year:"", city:"Jamestown", county:"Fentress", state:"Tennessee", region:"Middle TN", type:"Private", sites:30, hookup:"Full hookups, 30/50A", phone:"(931) 879-8080", web:"", tags:["Big South Fork area","Rural","Monthly rates"] },
  { name:"Big Puckett's Campground & RV Park", address:"1037 Austin Rd, Cookeville, TN 38583", year:"", city:"Cookeville", county:"Putnam", state:"Tennessee", region:"Middle TN", type:"Private", sites:35, hookup:"Full hookups, 30/50A", phone:"(931) 858-2253", web:"", tags:["Burgess Falls nearby","Caney Fork fishing"] },
  { name:"Tennessee River RV Resort", address:"185 S River Front Dr, Clifton, TN 37716", year:"", city:"Clifton", county:"Wayne", state:"Tennessee", region:"Middle TN", type:"Private", sites:40, hookup:"Full hookups, 30/50A, river access", phone:"", web:"", tags:["Tennessee River","Boat ramp"] },
  { name:"Coyote View RV Park", address:"2029 Phebus Ln, Union City, TN 38261", year:"", city:"Union City", county:"Obion", state:"Tennessee", region:"West TN", type:"Private", sites:30, hookup:"Full hookups, 30/50A", phone:"(731) 599-9898", web:"coyoteview.com", tags:["Reelfoot Lake area","RV repair on-site"] },
  { name:"Eagle's Nest RV Park", address:"100 Eagle Nest Rd, Buchanan, TN 38222", year:"", city:"Buchanan", county:"Henry", state:"Tennessee", region:"West TN", type:"Private", sites:33, hookup:"Full hookups (W/E/S), concrete pads, 30/50A", phone:"(731) 232-0222", web:"eaglesnesttn.com", tags:["Kentucky Lake","Fishing"] },
  { name:"Parker's Ridge RV Park", address:"460 Murphy Rd, Wildersville, TN 38388", year:"", city:"Wildersville", county:"Henderson", state:"Tennessee", region:"West TN", type:"Private", sites:40, hookup:"Full hookups, 30/50A", phone:"(731) 986-4894", web:"", tags:["Rural West TN","Monthly rates"] },
  { name:"Graceland RV Park & Campground", address:"3691 Elvis Presley Blvd, Memphis, TN 38116", year:"", city:"Memphis", county:"Shelby", state:"Tennessee", region:"West TN", type:"Private", sites:65, hookup:"Full hookups (W/E/S), pull-throughs", phone:"(901) 396-7125", web:"graceland.com/rv-park-campground", tags:["Memphis","Elvis Presley Blvd","Year-round"] },
  { name:"Thousand Trails Natchez Trace", address:"1363 Napier Rd, Hohenwald, TN 38462", year:"", city:"Hohenwald", county:"Lewis", state:"Tennessee", region:"West TN", type:"Private", sites:99, hookup:"Full hookups, 30/50A", phone:"(888) 707-1477", web:"thousandtrails.com", tags:["Membership park","Lake","Dog park","Pool"] },

  // ──────────────────────────────────────────────────────────
  //  TENNESSEE — LARGE PARKS, 100+ sites  (4 parks)
  // ──────────────────────────────────────────────────────────

  { name:"Greenbrier Campground", address:"2353 East Pkwy, Gatlinburg, TN 37738", year:"", city:"Gatlinburg", county:"Sevier", state:"Tennessee", region:"East TN", type:"Private", sites:120, hookup:"Full hookups, 20/30/50 amp, cable TV, WiFi", phone:"(865) 430-7415", web:"smokymountaincamping.com", tags:["Little Pigeon River","Near Greenbrier entrance to Smokies","Cabins available","River-frontage sites"] },
  { name:"Pigeon Forge/Gatlinburg KOA Holiday", address:"3122 Veterans Blvd, Pigeon Forge, TN 37863", year:"", city:"Pigeon Forge", county:"Sevier", state:"Tennessee", region:"East TN", type:"Private", sites:187, hookup:"Full hookups, 30/50 amp, cable, WiFi", phone:"(865) 453-7903", web:"koa.com", tags:["Big rig friendly","Pool","Near Dollywood","Cabins & pull-through sites"] },
  { name:"Pigeon Forge Landing RV Resort", address:"455 Lonesome Valley Rd, Sevierville, TN 37862", year:"", city:"Sevierville", county:"Sevier", state:"Tennessee", region:"East TN", type:"Private", sites:237, hookup:"Full hookups, 30/50/100 amp, concrete pads, cable, WiFi", phone:"(865) 446-1500", web:"rvcoutdoors.com", tags:["Little Pigeon River","Big rig friendly","Zip line & pool","Near Dollywood"] },
  { name:"Sun Outdoors Pigeon Forge", address:"1004 Parkway, Sevierville, TN 37862", year:"", city:"Sevierville", county:"Sevier", state:"Tennessee", region:"East TN", type:"Private", sites:297, hookup:"Full hookups, 20/30/50 amp, concrete pads, cable TV, WiFi", phone:"(800) 758-5267", web:"sunoutdoors.com", tags:["Formerly River Plantation RV Resort","On the Little Pigeon River","Lazy river pool","Big rig friendly"] },

  // ──────────────────────────────────────────────────────────
  //  ALABAMA  (8 parks)
  // ──────────────────────────────────────────────────────────

  { name:"Arrowhead RV Resort at Smith Lake", address:"761 County Rd 941, Crane Hill, AL 35053", year:"", city:"Crane Hill", county:"Cullman", state:"Alabama", region:"North AL", type:"Private", sites:60, hookup:"Full hookups, 30/50A, lakeside sites", phone:"(256) 739-6767", web:"arrowheadsmithlake.com", tags:["Lewis Smith Lake","Boat dock","Bar & Grill","Fishing"] },
  { name:"Desoto Caverns Family Campground", address:"5181 DeSoto Caverns Pkwy, Childersburg, AL 35044", year:"", city:"Childersburg", county:"Talladega", state:"Alabama", region:"North AL", type:"Private", sites:50, hookup:"Full hookups, 30A + some 50A", phone:"(256) 378-7252", web:"desotocavernspark.com", tags:["Caverns","Family activities","Talladega NF nearby"] },
  { name:"Noccalula Falls Campground", address:"1890 Noccalula Rd, Gadsden, AL 35901", year:"", city:"Gadsden", county:"Etowah", state:"Alabama", region:"North AL", type:"Private", sites:94, hookup:"Full hookups (W/E/S), pull-throughs, 30/50A", phone:"(256) 549-4663", web:"gadsdenal.gov/noccalula-falls-park", tags:["Waterfall","Pioneer Village","Pool","Miniature train"] },
  { name:"Bama RV Park", address:"5461 Skyland Blvd E, Cottondale, AL 35453", year:"", city:"Tuscaloosa", county:"Tuscaloosa", state:"Alabama", region:"Central AL", type:"Private", sites:60, hookup:"Full hookups (W/E/S), 30/50A", phone:"(205) 556-6063", web:"", tags:["University town","I-20/59 corridor","Monthly rates"] },
  { name:"Bohamia Glamping & RV", address:"2491 Berney Station Rd, Talladega, AL 35160", year:"", city:"Talladega", county:"Talladega", state:"Alabama", region:"Central AL", type:"Private", sites:30, hookup:"Electric + water, 30/50A", phone:"", web:"bohamia.com", tags:["Talladega NF","Glamping","Quiet","NASCAR area"] },
  { name:"Winner's Circle RV Resort", address:"7970 Bellingrath Rd, Theodore, AL 36582", year:"", city:"Theodore", county:"Mobile", state:"Alabama", region:"South AL", type:"Private", sites:99, hookup:"Full hookups (W/E/S), pull-throughs, 30/50A", phone:"(251) 653-9220", web:"", tags:["Mobile area","I-10 corridor","Monthly rates"] },
  { name:"Tropical Island RV Resort", address:"2252 Creek Winds Rd, Foley, AL 36535", year:"", city:"Foley", county:"Baldwin", state:"Alabama", region:"South AL", type:"Private", sites:85, hookup:"Full hookups, 30/50A, WiFi", phone:"(251) 943-3456", web:"", tags:["Gulf Shores area","Pool","15 min to beach"] },
  { name:"Lakeside Landing RV Park", address:"22206 US Hwy 431, Guntersville, AL 35976", year:"", city:"Guntersville", county:"Marshall", state:"Alabama", region:"North AL", type:"Private", sites:45, hookup:"Full hookups (W/E/S), 30/50A, waterfront sites", phone:"(256) 582-2622", web:"", tags:["Guntersville Lake","Fishing","Boat ramp"] },

  // ──────────────────────────────────────────────────────────
  //  ALABAMA — LARGE PARKS, 100+ sites  (5 parks)
  // ──────────────────────────────────────────────────────────

  { name:"Gulf Shores RV Resort", address:"18717 Barefoot Way, Gulf Shores, AL 36542", year:"", city:"Gulf Shores", county:"Baldwin", state:"Alabama", region:"South AL", type:"Private", sites:176, hookup:"Full hookups, 30/50 amp, water, sewer, cable, concrete pads", phone:"(251) 244-1015", web:"rvcoutdoors.com/gulf-shores-rv-resort", tags:["Waterfront lake sites","Heated pool","Pickleball","Stocked fishing lakes"] },
  { name:"Island Retreat RV Park", address:"18201 State Highway 180, Gulf Shores, AL 36542", year:"", city:"Gulf Shores", county:"Baldwin", state:"Alabama", region:"South AL", type:"Private", sites:173, hookup:"Full hookups, 20/30/50 amp, concrete pads", phone:"(251) 967-1666", web:"islandretreatrvpark.com", tags:["Pull-thru & back-in sites","Pool","Clubhouse","RVs only, 15-years-or-newer rule"] },
  { name:"Bay Palms RV Resort", address:"15440 Dauphin Island Pkwy, Coden, AL 36523", year:"", city:"Coden", county:"Mobile", state:"Alabama", region:"South AL", type:"Private", sites:170, hookup:"Full hookups, 30/50 amp, sewer, paved sites", phone:"(251) 873-4700", web:"baypalmsrvresort.com", tags:["Big rig friendly (up to 70 ft)","Pool","Dog park","RV-only resort"] },
  { name:"Sun Outdoors Orange Beach", address:"22800 Canal Rd, Orange Beach, AL 36561", year:"", city:"Orange Beach", county:"Baldwin", state:"Alabama", region:"South AL", type:"Private", sites:142, hookup:"Full hookups, some pull-thru sites", phone:"(844) 707-4343", web:"sunoutdoors.com/alabama/sun-outdoors-orange-beach", tags:["Pull-thru sites","Resort amenities","Year-round"] },
  { name:"Two Lakes RV Resort", address:"22353 Twin Lakes Circle, Gulf Shores, AL 36542", year:"", city:"Gulf Shores", county:"Baldwin", state:"Alabama", region:"South AL", type:"Private", sites:110, hookup:"Full hookups, 50 amp only, concrete pads, cable/fiber WiFi", phone:"(251) 714-2709", web:"twolakesrvresort.com", tags:["Lakeside premium sites","Pool","Clubhouse","Pickleball"] },

  // ──────────────────────────────────────────────────────────
  //  NORTH CAROLINA  (10 parks)
  // ──────────────────────────────────────────────────────────

  { name:"Creekwood Farm RV Park", address:"4696 Jonathan Creek Rd, Waynesville, NC 28785", year:"", city:"Maggie Valley", county:"Haywood", state:"North Carolina", region:"Mountains NC", type:"Private", sites:55, hookup:"Full hookups, 30/50A, pull-throughs", phone:"(828) 926-7977", web:"creekwoodfarm.com", tags:["Nantahala NF gateway","Jonathan Creek","Cherokee area"] },
  { name:"Foxfire Mountain RV Sites", address:"1820 Tilson Rd, Murphy, NC 28906", year:"", city:"Murphy", county:"Cherokee", state:"North Carolina", region:"Mountains NC", type:"Private", sites:40, hookup:"Full hookups, 30/50A, WiFi", phone:"(828) 835-9706", web:"foxfiremountain.com", tags:["Western NC","Mountain views","Quiet"] },
  { name:"Mama Gertie's Hideaway Campground", address:"15 Uphill Rd, Swannanoa, NC 28778", year:"", city:"Swannanoa", county:"Buncombe", state:"North Carolina", region:"Mountains NC", type:"Private", sites:60, hookup:"Full hookups, 30/50A, WiFi", phone:"(828) 686-4258", web:"campmamagertie.com", tags:["Asheville area","River access","Hiking","Annual events"] },
  { name:"Black Bear Campground", address:"6192 Lake James Rd, Marion, NC 28752", year:"", city:"Marion", county:"McDowell", state:"North Carolina", region:"Mountains NC", type:"Private", sites:75, hookup:"Full hookups (W/E/S), 30/50A, pull-throughs", phone:"(828) 652-7928", web:"blackbearnc.com", tags:["Linville Gorge area","Lake Tahoma","Pool","WiFi"] },
  { name:"Bear Den Campground", address:"600 Bear Den Mountain Rd, Spruce Pine, NC 28777", year:"", city:"Spruce Pine", county:"Mitchell", state:"North Carolina", region:"Mountains NC", type:"Private", sites:95, hookup:"Full hookups, 30/50A, pull-throughs", phone:"(828) 765-2888", web:"beardencampground.com", tags:["Blue Ridge Pkwy area","Gem mining nearby","Pool","WiFi"] },
  { name:"Asheville West KOA", address:"309 Wiggins Rd, Candler, NC 28715", year:"", city:"Candler", county:"Buncombe", state:"North Carolina", region:"Mountains NC", type:"Private", sites:85, hookup:"Full hookups (W/E/S), 30/50A, WiFi", phone:"(828) 665-7015", web:"koa.com/campgrounds/asheville-west", tags:["Asheville area","Pool","Mountain views"] },
  { name:"Hound's Campground", address:"114 Raven Circle, Kings Mountain, NC 28086", year:"", city:"Gastonia", county:"Gaston", state:"North Carolina", region:"Piedmont NC", type:"Private", sites:45, hookup:"Full hookups, 30/50A", phone:"(704) 922-5723", web:"", tags:["Crowders Mountain area","Charlotte day trip"] },
  { name:"Jordan Lake Campground & Marina", address:"389 Fearrington Rd, Apex, NC 27502", year:"", city:"Pittsboro", county:"Chatham", state:"North Carolina", region:"Piedmont NC", type:"Private", sites:60, hookup:"Full hookups, 30/50A, WiFi", phone:"(919) 542-5600", web:"jordanlakecampground.com", tags:["Jordan Lake","Boat ramp","Fishing","Raleigh area"] },
  { name:"Cape Hatteras KOA Resort", address:"25099 NC Hwy 12, Rodanthe, NC 27968", year:"", city:"Rodanthe", county:"Dare", state:"North Carolina", region:"Coastal NC", type:"Private", sites:90, hookup:"Full hookups (W/E/S), 30/50A, WiFi, pool", phone:"(252) 987-2307", web:"koa.com/campgrounds/cape-hatteras", tags:["Outer Banks","Beach access","Kiteboarding","Fishing"] },
  { name:"Frisco Woods Campground", address:"53124 NC 12 Hwy, Frisco, NC 27936", year:"", city:"Frisco", county:"Dare", state:"North Carolina", region:"Coastal NC", type:"Private", sites:96, hookup:"Full hookups (W/E/S), 30/50A, WiFi", phone:"(252) 995-5208", web:"outer-banks.com/friscwoods", tags:["Outer Banks","Sound access","Windsurfing","Kiteboarding"] },

  // ──────────────────────────────────────────────────────────
  //  NORTH CAROLINA — LARGE PARKS, 100+ sites  (4 parks)
  // ──────────────────────────────────────────────────────────

  { name:"Camp Hatteras RV Resort", address:"24798 NC Hwy 12, Rodanthe, NC 27968", year:"", city:"Rodanthe", county:"Dare", state:"North Carolina", region:"Coastal NC", type:"Private", sites:403, hookup:"Full hookups (W/E/S), 30/50A, concrete pads", phone:"(252) 987-2777", web:"camphatteras.com", tags:["Outer Banks","Oceanfront to soundfront","Concrete pads","Big rig friendly"] },
  { name:"Cape Woods Campground", address:"47649 Buxton Back Rd, Buxton, NC 27920", year:"", city:"Buxton", county:"Dare", state:"North Carolina", region:"Coastal NC", type:"Private", sites:130, hookup:"Full and partial hookups (W/E/S), 30/50A, pull-throughs", phone:"(252) 996-3600", web:"capewoods.com", tags:["Outer Banks","Hatteras Island","Pool","Near Cape Hatteras Lighthouse"] },
  { name:"Camping World Racing Resort", address:"6600 Bruton Smith Blvd, Concord, NC 28027", year:"", city:"Concord", county:"Cabarrus", state:"North Carolina", region:"Piedmont NC", type:"Private", sites:380, hookup:"Full hookups (W/E/S), 30/50A", phone:"(704) 455-4445", web:"charlottemotorspeedway.com", tags:["Charlotte Motor Speedway","Year-round camping","Big rig friendly","NASCAR events nearby"] },
  { name:"Emerald Isle RV Resort", address:"9102 Coast Guard Rd, Emerald Isle, NC 28594", year:"", city:"Emerald Isle", county:"Carteret", state:"North Carolina", region:"Coastal NC", type:"Private", sites:313, hookup:"Full hookups, 30/50A, water, sewer, grassy pull-through sites", phone:"(252) 354-2250", web:"emeraldislervresort.com", tags:["Crystal Coast","Oceanfront","Pool","Big rig friendly"] },

  // ──────────────────────────────────────────────────────────
  //  SOUTH CAROLINA  (7 parks)
  // ──────────────────────────────────────────────────────────

  { name:"The Point at Lake Hartwell RV Resort", address:"400 Ponderosa Point Rd, Townville, SC 29689", year:"", city:"Townville", county:"Anderson", state:"South Carolina", region:"Upstate SC", type:"Private", sites:65, hookup:"Full hookups, 30/50A, waterfront sites", phone:"(864) 287-3376", web:"thepointatlakerv.com", tags:["Hartwell Lake","Boat ramp","Fishing","Swimming"] },
  { name:"Clemson RV Park at the Grove", address:"150 Dalton Dr, Pendleton, SC 29670", year:"", city:"Clemson", county:"Pickens", state:"South Carolina", region:"Upstate SC", type:"Private", sites:97, hookup:"Full hookups (W/E/S), 30/50A, paved pads", phone:"(864) 654-2626", web:"clemsonrv.com", tags:["Clemson area","Lake Hartwell access","WiFi","Year-round"] },
  { name:"River Bottom Farms Campground", address:"357 Cedar Creek Rd, Swansea, SC 29160", year:"", city:"Leesville", county:"Lexington", state:"South Carolina", region:"Midlands SC", type:"Private", sites:75, hookup:"Full hookups, 30/50A, pull-throughs", phone:"(803) 532-2854", web:"riverbottomfarms.com", tags:["Lake Murray area","Farm setting","Pool","Columbia day trip"] },
  { name:"Edmund RV Park", address:"5910 Edmund Hwy, Lexington, SC 29073", year:"", city:"Edmund", county:"Lexington", state:"South Carolina", region:"Midlands SC", type:"Private", sites:50, hookup:"Full hookups (W/E/S), 30/50A", phone:"(803) 732-0888", web:"", tags:["Congaree NP nearby","Lake Murray area","Monthly rates"] },
  { name:"Sesquicentennial State Park - Camp Lake Adger", address:"9564 Two Notch Rd, Columbia, SC 29223", year:"", city:"Columbia", county:"Richland", state:"South Carolina", region:"Midlands SC", type:"Private", sites:87, hookup:"Full hookups, 30/50A, WiFi", phone:"(803) 788-2706", web:"", tags:["Columbia area","Lake","Fishing","Quiet pines"] },
  { name:"Oaks at Point South RV Resort", address:"1292 Campground Rd, Yemassee, SC 29945", year:"", city:"Yemassee", county:"Hampton", state:"South Carolina", region:"Lowcountry SC", type:"Private", sites:95, hookup:"Full hookups (W/E/S), 30/50A, pull-throughs", phone:"(843) 726-5728", web:"oaksatpointsouth.com", tags:["I-95 corridor","Hilton Head day trip","Pool","WiFi"] },
  { name:"Savannah Lakes RV Resort", address:"170 Savannah Lakes Dr, Hardeeville, SC 29927", year:"", city:"Hardeeville", county:"Jasper", state:"South Carolina", region:"Lowcountry SC", type:"Private", sites:90, hookup:"Full hookups (W/E/S), 30/50A, WiFi", phone:"(843) 784-2313", web:"savannahlakesrv.com", tags:["Near Savannah GA","Pool","Hot tub","Birding"] },

  // ──────────────────────────────────────────────────────────
  //  SOUTH CAROLINA — LARGE PARKS, 100+ sites  (5 parks)
  // ──────────────────────────────────────────────────────────

  { name:"Ocean Lakes Family Campground", address:"6001 South Kings Hwy, Myrtle Beach, SC 29575", year:"", city:"Myrtle Beach", county:"Horry", state:"South Carolina", region:"Grand Strand SC", type:"Private", sites:859, hookup:"20/30/50A electric, water, sewer, cable TV, concrete pads on most sites", phone:"(877) 510-1413", web:"oceanlakes.com", tags:["Oceanfront","One-mile beachfront","Family campground","Big rig friendly"] },
  { name:"Lakewood Camping Resort", address:"5901 S Kings Hwy, Myrtle Beach, SC 29575", year:"", city:"Myrtle Beach", county:"Horry", state:"South Carolina", region:"Grand Strand SC", type:"Private", sites:1043, hookup:"Full hookups, 20/30/50A, water, sewer", phone:"(843) 238-5161", web:"lakewoodcampground.com", tags:["Oceanfront","Lakefront sites","Water park","Pet-friendly"] },
  { name:"WillowTree RV Resort", address:"520 Southern Sights Dr, Longs, SC 29568", year:"", city:"Longs", county:"Horry", state:"South Carolina", region:"Grand Strand SC", type:"Private", sites:107, hookup:"Full hookups, 20/30/50A, paved pull-through sites", phone:"(843) 756-4334", web:"willowtreervr.com", tags:["Paved pull-throughs","Big rig friendly","Fire rings","Concrete patios"] },
  { name:"Hilton Head Island Motorcoach Resort", address:"133 Arrow Rd, Hilton Head Island, SC 29928", year:"", city:"Hilton Head Island", county:"Beaufort", state:"South Carolina", region:"Lowcountry SC", type:"Private", sites:401, hookup:"Full hookups, 30/50A, water, sewer, cable TV (motorcoach only)", phone:"(843) 785-7699", web:"hhimotorcoachresort.com", tags:["Motorcoach-only resort","Gated","Pool & hot tub","Pickleball","Dog park"] },
  { name:"Oak Plantation Campground", address:"3540 Savannah Hwy, Johns Island, SC 29455", year:"", city:"Johns Island", county:"Charleston", state:"South Carolina", region:"Lowcountry SC", type:"Private", sites:298, hookup:"20/30/50A, full-hookup and pull-through sites", phone:"(843) 766-5936", web:"oakplantationcampground.com", tags:["Near Charleston","Pull-through sites","Pool","Big rig friendly"] },

  // ──────────────────────────────────────────────────────────
  //  TEXAS  (54 parks)
  // ──────────────────────────────────────────────────────────

  { name:"Dos Rios RV Park", address:"4500 Dos Rios Trail, Mason, TX 76856", year:"", city:"Mason", county:"Mason", state:"Texas", region:"Hill Country TX", type:"Private", sites:19, hookup:"Full hookups, riverfront sites", phone:"(512) 553-3977", web:"dosriosrvpark.com", tags:["Llano River","Dog-friendly","Stargazing","Fredericksburg nearby"] },
  { name:"Nestled Pines RV Park", address:"458 County Rd 466, Etoile, TX 75944", year:"", city:"Etoile", county:"Nacogdoches", state:"Texas", region:"East TX", type:"Private", sites:15, hookup:"Full hookups, 20/30/50A, fiber WiFi", phone:"(936) 556-0012", web:"nestledpinesrvpark.com", tags:["Piney Woods","Lake Sam Rayburn","Small park","Quiet"] },
  { name:"The Pines RV & Cabin Resort", address:"4069 County Rd SE 4250, Mount Vernon, TX 75457", year:"", city:"Mount Vernon", county:"Franklin", state:"Texas", region:"East TX", type:"Private", sites:65, hookup:"Full hookups, concrete pads, pull-throughs", phone:"(903) 860-2680", web:"thepinesrvcabinresort.com", tags:["Lake Cypress Springs","Lake Bob Sandlin","Pool","Dog parks"] },
  { name:"Shady Hill RV Park", address:"10700 Jacksboro Hwy, Fort Worth, TX 76135", year:"", city:"Fort Worth", county:"Tarrant", state:"Texas", region:"North TX", type:"Private", sites:60, hookup:"Full hookups, paved sites", phone:"(817) 229-3817", web:"shadyhillrvpark.com", tags:["Lake Worth","Eagle Mountain Lake","Shade trees"] },
  { name:"Pecan Acres RV Park", address:"12667 S FM 730, Azle, TX 76020", year:"", city:"Azle", county:"Tarrant", state:"Texas", region:"North TX", type:"Private", sites:84, hookup:"Full hookups, 30/50A", phone:"(817) 688-9316", web:"pecanacresrvpark.net", tags:["Pecan grove","Fort Worth area","Shaded sites"] },
  { name:"Cotton Land RV Park", address:"5040 E Hwy 62-82, Lubbock, TX 79403", year:"", city:"Lubbock", county:"Lubbock", state:"Texas", region:"Panhandle TX", type:"Private", sites:25, hookup:"Electric + water, back-in and pull-through", phone:"(806) 319-5280", web:"cottonlandrv.com", tags:["Family-owned","Laundry facility"] },
  { name:"Triangle RV Park", address:"500 Orient St, Claude, TX 79019", year:"", city:"Claude", county:"Armstrong", state:"Texas", region:"Panhandle TX", type:"Private", sites:30, hookup:"Full hookups, 30/50A, water", phone:"(806) 433-5671", web:"trianglervpark.com", tags:["Near Amarillo","Pet friendly","24-hour access"] },
  { name:"Overnite RV Park", address:"900 S Lakeside Dr, Amarillo, TX 79118", year:"", city:"Amarillo", county:"Potter", state:"Texas", region:"Panhandle TX", type:"Private", sites:79, hookup:"Full hookups, pull-through sites", phone:"(806) 373-1431", web:"overnitervpark.com", tags:["I-40 corridor","Long-term stays","Route 66"] },
  { name:"Hackberry Acres RV Park", address:"403 Hackberry St, Clifton, TX 76634", year:"", city:"Clifton", county:"Bosque", state:"Texas", region:"Central TX", type:"Private", sites:22, hookup:"Full hookups, 20/30/50A, pull-throughs", phone:"(254) 633-3363", web:"hackberryacresrvpark.com", tags:["Bosque River","Walkable downtown","Big-rig friendly"] },

  { name:"Texas Gulf RV Park", address:"115 N Byers Dr, Port O'Connor, TX 77982", year:"", city:"Port O'Connor", county:"Calhoun", state:"Texas", region:"Gulf Coast TX", type:"Private", sites:27, hookup:"Full hookups, 20/30/50 amp electric", phone:"", web:"", tags:["Small in-town park","Near Port O'Connor harbor","Matagorda Bay fishing"] },
  { name:"Port O'Connor RV Park", address:"110 Steve Street, Port O'Connor, TX 77982", year:"", city:"Port O'Connor", county:"Calhoun", state:"Texas", region:"Gulf Coast TX", type:"Private", sites:71, hookup:"Full hookups, 50/30/20 amp", phone:"(361) 484-9737", web:"pocrvp.com", tags:["Swimming pool & hot tub","Near Matagorda Bay","Gulf Coast fishing town"] },
  { name:"Beacon 44 RV Park", address:"1982 W. Harrison Ave, Port O'Connor, TX 77982", year:"", city:"Port O'Connor", county:"Calhoun", state:"Texas", region:"Gulf Coast TX", type:"Private", sites:50, hookup:"30/50 amp electric, water, sewer, gravel pads", phone:"(361) 983-4247", web:"beacon44rvpark.com", tags:["Stocked fishing pond","Near Matagorda Island","Off Highway 185"] },
  { name:"Caney Creek RV Park", address:"230 County Road 285, Sargent, TX 77414", year:"", city:"Sargent", county:"Matagorda", state:"Texas", region:"Gulf Coast TX", type:"Private", sites:32, hookup:"Full hookups, 30/50 amp, concrete pads", phone:"(979) 245-4735", web:"caneycreekrv.com", tags:["Boat ramp & fish cleaning station","Family owned since 2001","Caney Creek access"] },
  { name:"Sargent Beach RV Park", address:"27466 FM 457, Sargent, TX 77414", year:"", city:"Sargent", county:"Matagorda", state:"Texas", region:"Gulf Coast TX", type:"Private", sites:7, hookup:"30/50 amp electric, water, sewer", phone:"(979) 529-5295", web:"sargentbeachrvpark.com", tags:["Directly on Sargent Beach","Between Gulf and Intracoastal Waterway","Concrete pads, big-rig friendly"] },

  { name:"RV Haven", address:"922 Mack Rd, Aransas Pass, TX 78336", year:"", city:"Aransas Pass", county:"San Patricio", state:"Texas", region:"Coastal Bend TX", type:"Private", sites:14, hookup:"Full hookups, 30/50/110 amp", phone:"(361) 238-5483", web:"rvhavenrockport.com", tags:["Near Rockport & Port Aransas","Oak-shaded sites","Small quiet retreat"] },
  { name:"Live Oak Point RV Park", address:"4730 Texas Business 35 N, Rockport, TX 78382", year:"", city:"Rockport", county:"Aransas", state:"Texas", region:"Coastal Bend TX", type:"Private", sites:23, hookup:"Water, electric, sewer (septic), concrete pads", phone:"(361) 238-0995", web:"liveoakpointrv.com", tags:["Aransas Bay waterfront","Long fishing pier","Dog-friendly","Near Copano Bridge"] },
  { name:"Driftwood RV Park", address:"701 Mesquite St, Fulton, TX 78358", year:"", city:"Fulton", county:"Aransas", state:"Texas", region:"Coastal Bend TX", type:"Private", sites:56, hookup:"Full hookups", phone:"(361) 729-2452", web:"driftwoodrvrockport.com", tags:["Close to Aransas Bay","Near downtown Rockport-Fulton"] },
  { name:"Sunrise RV Resort", address:"701 Myrtle St, Fulton, TX 78358", year:"", city:"Fulton", county:"Aransas", state:"Texas", region:"Coastal Bend TX", type:"Private", sites:79, hookup:"Full hookups, 30/50 amp, pull-through sites", phone:"(361) 360-4822", web:"sunriservresort.com", tags:["Half mile from downtown Fulton","3 miles to Rockport Beach","Pool"] },
  { name:"Coastal Cowboy RV Park - Fulton", address:"3639 TX-35, Rockport, TX 78382", year:"", city:"Rockport", county:"Aransas", state:"Texas", region:"Coastal Bend TX", type:"Private", sites:39, hookup:"Full hookups, 20/30/50 amp, pull-thrus", phone:"(361) 775-5230", web:"coastalcowboyrvpark.com", tags:["Aransas Bay views","Near Fulton","Activity center"] },

  { name:"D&L RV Park", address:"151 Minnesota Rd, Alamo, TX 78516", year:"", city:"Alamo", county:"Hidalgo", state:"Texas", region:"Rio Grande Valley TX", type:"Private", sites:9, hookup:"Full hookups, 30/50 amp, paved roads", phone:"(956) 929-4154", web:"", tags:["Tiny park","Home-style RV park","Pet friendly","Shuffleboard"] },
  { name:"Monte Cristo Golf & Country Club RV Park", address:"2919 N Kenyon Rd, Edinburg, TX 78542", year:"", city:"Edinburg", county:"Hidalgo", state:"Texas", region:"Rio Grande Valley TX", type:"Private", sites:20, hookup:"Full hookups, 30/50 amp", phone:"(866) 576-5333", web:"montecristogcc.com", tags:["Golf course access","Clubhouse","Swimming pool","55+ friendly"] },
  { name:"Sundance RV Village", address:"6101 W Business 83, Harlingen, TX 78552", year:"", city:"Harlingen", county:"Cameron", state:"Texas", region:"Rio Grande Valley TX", type:"Private", sites:77, hookup:"Full hookups, 30/50 amp, pull-through sites", phone:"(956) 423-8314", web:"sundancervresort.com", tags:["Gated","Clubhouse","Shuffleboard","Big rig friendly"] },
  { name:"La Floresta RV Park & Golf Course", address:"4140 La Floresta, Mercedes, TX 78570", year:"", city:"Mercedes", county:"Hidalgo", state:"Texas", region:"Rio Grande Valley TX", type:"Private", sites:92, hookup:"Full hookups, 30/50 amp", phone:"(956) 565-6314", web:"laflorestarvpark.com", tags:["Golf course","Historic 1929 estate grounds","Clubhouse","55+ community"] },

  { name:"Terlingua Ranch Lodge RV Park", address:"16000 Terlingua Ranch Rd, Terlingua, TX 79852", year:"", city:"Terlingua", county:"Brewster", state:"Texas", region:"Big Bend TX", type:"Private", sites:20, hookup:"15/20/30/50 amp electric, water, sewer at pull-throughs", phone:"(432) 371-3146", web:"terlinguaranch.com", tags:["Near Big Bend National Park","Pool and restaurant","Mountain views"] },
  { name:"Tumble In RV Park", address:"93320 US Hwy 90 E, Marfa, TX 79843", year:"", city:"Marfa", county:"Presidio", state:"Texas", region:"Big Bend TX", type:"Private", sites:22, hookup:"20/30/50 amp electric, water, some sewer, dump station", phone:"(432) 301-9860", web:"tumbleinmarfa.com", tags:["Locally owned","Level gravel sites","Free WiFi","Near Marfa Lights"] },
  { name:"Study Butte RV Park", address:"53751 TX-118, Terlingua, TX 79852", year:"", city:"Terlingua", county:"Brewster", state:"Texas", region:"Big Bend TX", type:"Private", sites:10, hookup:"Full hookups, 30 amp, RVs only up to 40 ft", phone:"(432) 371-2468", web:"", tags:["Closest RV park to Big Bend NP entrance","RV-only park","On-site store"] },
  { name:"Marathon Motel & RV Park", address:"701 US-90, Marathon, TX 79842", year:"", city:"Marathon", county:"Brewster", state:"Texas", region:"Big Bend TX", type:"Private", sites:29, hookup:"Full hookups", phone:"(432) 386-4241", web:"marathonmotel.com", tags:["Motel and RV combo","Gateway to Big Bend","Historic Marathon"] },
  { name:"Cliffhanger RV Park", address:"45978 State Highway 118 S, Alpine, TX 79830", year:"", city:"Alpine", county:"Brewster", state:"Texas", region:"Big Bend TX", type:"Private", sites:6, hookup:"Full hookups, 30/50 amp, dump station, max 50 ft", phone:"", web:"", tags:["Small 6-site park","Rustic, off-the-beaten-path","Pet friendly"] },

  { name:"Cactus Draw R.V. Park", address:"1306 North Birdwell Lane, Big Spring, TX 79720", year:"", city:"Big Spring", county:"Howard", state:"Texas", region:"Permian Basin TX", type:"Private", sites:17, hookup:"Full hookups, 30/50 amp", phone:"(817) 205-8138", web:"cactusdrawrv.com", tags:["North of I-20","Nestled in trees","13 acres of trails","Cabin rentals"] },
  { name:"Our Place RV Park", address:"6804 South Service Road, Big Spring, TX 79720", year:"", city:"Big Spring", county:"Howard", state:"Texas", region:"Permian Basin TX", type:"Private", sites:20, hookup:"Full hookups, 30/50 amp, pull-through", phone:"(432) 287-1302", web:"", tags:["Pull-through sites","On I-20 service road","Dog park","Strong WiFi"] },
  { name:"Gil's RV Korral", address:"7105 Grape Creek Road, San Angelo, TX 76901", year:"", city:"San Angelo", county:"Tom Green", state:"Texas", region:"Permian Basin TX", type:"Private", sites:14, hookup:"Full hookups, 30/50 amp, no dump station", phone:"(325) 277-6847", web:"", tags:["24-hour access","On-site laundromat","Long-term stays"] },
  { name:"Castaway RV Park", address:"7551 West 26th Street, Odessa, TX 79763", year:"", city:"Odessa", county:"Ector", state:"Texas", region:"Permian Basin TX", type:"Private", sites:20, hookup:"Full hookups, 30/50 amp", phone:"(432) 381-5552", web:"castawayrvparks.com", tags:["Family operated","Quiet & private","Shaded sites"] },

  { name:"Yanawana Camp", address:"2322 E Chavaneaux Rd, San Antonio, TX 78214", year:"", city:"San Antonio", county:"Bexar", state:"Texas", region:"South TX", type:"Private", sites:5, hookup:"Full hookups, 20/30/50 amp, gravel back-in sites", phone:"(512) 496-8893", web:"yanawanacamp.com", tags:["Near Mission San Juan","San Antonio Missions Trail","2.4 acres","Pet friendly"] },
  { name:"Rio Guadalupe Resort", address:"14130 River Rd, New Braunfels, TX 78132", year:"", city:"New Braunfels", county:"Comal", state:"Texas", region:"South TX", type:"Private", sites:64, hookup:"Full hookups, 30/50 amp, cable, WiFi", phone:"(830) 964-3613", web:"rioguadaluperesort.com", tags:["Guadalupe River frontage","Tubing & kayaking","Near Canyon Lake","Open since 1976"] },
  { name:"Little RV Spot", address:"1574 Westward Trail, Uvalde, TX 78801", year:"", city:"Uvalde", county:"Uvalde", state:"Texas", region:"South TX", type:"Private", sites:22, hookup:"Full hookups, 30/50 amp, gravel back-in sites", phone:"(830) 931-5109", web:"thelittlervspot.com", tags:["Big rig friendly","Self-service RV wash","Near Frio River"] },
  { name:"Hidden Valley RV Park", address:"5706 Coleman Way, Von Ormy, TX 78073", year:"", city:"Von Ormy", county:"Bexar", state:"Texas", region:"South TX", type:"Private", sites:74, hookup:"Full hookups, 30/50 amp, concrete & gravel pads", phone:"(210) 623-6737", web:"hiddenvalleyrvpark.com", tags:["Medio Creek frontage","Dog park","2025 Campspot Award winner"] },
  { name:"The Dam Park", address:"961 Lakeside Pass, New Braunfels, TX 78130", year:"", city:"New Braunfels", county:"Comal", state:"Texas", region:"South TX", type:"Private", sites:45, hookup:"Full hookups, WiFi included", phone:"(830) 282-0662", web:"thedampark.com", tags:["Guadalupe River access","Riverfront cabanas","Locally owned","Dog park"] },

  { name:"Tall Timbers RV Park", address:"16614 Echo Glen Dr, Tyler, TX 75703", year:"", city:"Tyler", county:"Smith", state:"Texas", region:"East TX", type:"Private", sites:14, hookup:"Full hookups, concrete pads, 30/50A", phone:"(903) 871-5760", web:"ttrv.com", tags:["South Tyler","Concrete pads","All bills paid","Small park"] },
  { name:"Buffalo Run RV Park", address:"1800 US Highway 59 N, Jefferson, TX 75657", year:"", city:"Jefferson", county:"Marion", state:"Texas", region:"East TX", type:"Private", sites:28, hookup:"Full hookups, 30/50A, pull-through sites", phone:"(903) 665-4250", web:"buffalorunrvpark.net", tags:["Near Caddo Lake","Historic Jefferson","Pull-through","Pet friendly"] },
  { name:"Home Sweet Home RV Park", address:"6451 W 7th St, Texarkana, TX 75501", year:"", city:"Texarkana", county:"Bowie", state:"Texas", region:"East TX", type:"Private", sites:48, hookup:"Full hookups, 30/50A", phone:"(903) 838-4462", web:"homesweethomervpark.com", tags:["I-30 access","RV-only park","Pet friendly"] },
  { name:"Cypress Valley RV Park", address:"8838 US Highway 59 N, Marshall, TX 75670", year:"", city:"Marshall", county:"Harrison", state:"Texas", region:"East TX", type:"Private", sites:57, hookup:"Full hookups, 20/30/50A, pull-through sites", phone:"(903) 938-8844", web:"cypressvalleyrvparktx.com", tags:["Near Jefferson","Fishing pond","Big rig friendly"] },
  { name:"Southern Pines RV Campground", address:"5264 Ted Trout Dr, Lufkin, TX 75904", year:"", city:"Lufkin", county:"Angelina", state:"Texas", region:"East TX", type:"Private", sites:33, hookup:"Full hookups, 100% concrete pads, 20/30/50A", phone:"(903) 707-0660", web:"southernpinesrvcampground.com", tags:["100% concrete pads","Dog park","Pool","Pet friendly"] },

  { name:"Cozy Hill RV and Cabin Resort", address:"2110 N FM 51, Weatherford, TX 76086", year:"", city:"Weatherford", county:"Parker", state:"Texas", region:"North TX", type:"Private", sites:48, hookup:"Full hookups, 20/30/50 amp", phone:"(817) 408-0800", web:"cozyhillrvandcabinresort.com", tags:["Pond","Creek frontage","Cabin rentals","Walking trails"] },
  { name:"Hooves N Wheels RV Park & Horse Motel", address:"4128 Granbury Hwy, Weatherford, TX 76087", year:"", city:"Weatherford", county:"Parker", state:"Texas", region:"North TX", type:"Private", sites:52, hookup:"Full hookups, 30/50 amp, pull-through and back-in", phone:"(817) 599-4686", web:"hoovesnwheels.com", tags:["Horse motel","Family owned","Dog park","Big rig friendly"] },
  { name:"Rockett RV Ranch", address:"3160 FM 813, Palmer, TX 75152", year:"", city:"Palmer", county:"Ellis", state:"Texas", region:"North TX", type:"Private", sites:36, hookup:"Full hookups, 20/30/50 amp, hard-surface sites", phone:"(469) 658-6557", web:"rockettrvranch.com", tags:["Clubhouse","Near Waxahachie","Daily laundry","Free WiFi"] },
  { name:"McWest RV Park", address:"727 E Cottage Hill Pkwy, McKinney, TX 75071", year:"", city:"McKinney", county:"Collin", state:"Texas", region:"North TX", type:"Private", sites:30, hookup:"Water/sewer hookups, 20/30/50 amp, back-in sites", phone:"(214) 714-4318", web:"mcwestrvpark.com", tags:["Back-in sites","Pet friendly","Collin County"] },

  { name:"Buddy's Backyard RV Resort", address:"401 Stagecoach Ranch Rd, Dripping Springs, TX 78620", year:"", city:"Dripping Springs", county:"Travis", state:"Texas", region:"Austin Area TX", type:"Private", sites:75, hookup:"Full hookups, 30/50 amp", phone:"(512) 800-8033", web:"buddysbackyardrv.com", tags:["Hill Country views","Pool & clubhouse","Pet friendly"] },
  { name:"Pecan Grove RV Park", address:"1518 Barton Springs Rd, Austin, TX 78704", year:"", city:"Austin", county:"Travis", state:"Texas", region:"Austin Area TX", type:"Private", sites:93, hookup:"Full hookups, 30/50 amp", phone:"(512) 472-1067", web:"", tags:["Walk to Zilker Park","Near Barton Springs Pool","Shaded by pecan trees","Downtown Austin"] },
  { name:"Riverbend RV Park on Lake Austin", address:"12405 River Bend, Austin, TX 78732", year:"", city:"Austin", county:"Travis", state:"Texas", region:"Austin Area TX", type:"Private", sites:5, hookup:"Full hookup pads", phone:"(512) 694-0094", web:"riverbendaustin.com", tags:["Lake Austin waterfront","Kayak access","Tiny 5-site park"] },
  { name:"Reagan Ridge RV Park", address:"26690 Ronald W Reagan Blvd, Georgetown, TX 78633", year:"", city:"Georgetown", county:"Williamson", state:"Texas", region:"Austin Area TX", type:"Private", sites:71, hookup:"Full hookups, 20/30/50 amp, city water", phone:"(512) 829-0033", web:"reaganridgerv.com", tags:["Adult-focused, quiet","Pool","Free WiFi"] },

  { name:"Abilene RV Park", address:"6195 E Hwy 80, Abilene, TX 79601", year:"", city:"Abilene", county:"Taylor", state:"Texas", region:"Panhandle TX", type:"Private", sites:66, hookup:"Full hookups, 30/50 amp, pull-thru sites", phone:"(325) 672-2212", web:"abilenetexasrvpark.com", tags:["Swimming pool","Laundry","Pet-friendly"] },
  { name:"Shady Lane RV Park", address:"2010 East 5th Street, Plainview, TX 79072", year:"", city:"Plainview", county:"Hale", state:"Texas", region:"Panhandle TX", type:"Private", sites:48, hookup:"Full hookups, 20/30/50 amp", phone:"(806) 518-5985", web:"shadylanervparktx.com", tags:["Family-owned","Shade trees","24/7 on-site managers"] },
  { name:"Back Forty RV Park", address:"2062 FM 2568, Quanah, TX 79252", year:"", city:"Quanah", county:"Hardeman", state:"Texas", region:"Panhandle TX", type:"Private", sites:40, hookup:"Full hookups, 30/50 amp, gravel pads", phone:"(940) 839-8874", web:"backfortyrv.com", tags:["Veteran-owned","Near Childress","Big-rig friendly"] },
  { name:"Rocking A RV Park", address:"3725 Harrison St, Vernon, TX 76384", year:"", city:"Vernon", county:"Wilbarger", state:"Texas", region:"Panhandle TX", type:"Private", sites:77, hookup:"Full hookups, 30/50 amp, pull-thru grass sites", phone:"(940) 552-2821", web:"rockingarvpark.com", tags:["Shade trees","Swimming pool","Near Wichita Falls"] },

  // ──────────────────────────────────────────────────────────
  //  TEXAS — LARGE PARKS, 100+ sites  (8 parks)
  //  Bigger resorts we track for reference — outside the site's
  //  usual small-park focus, shown under each state's "100+" tab.
  // ──────────────────────────────────────────────────────────

  { name:"DFW Mid-Cities RV Park", address:"4620 Kennedale New Hope Road, Fort Worth, TX 76140", year:"", city:"Fort Worth", county:"Tarrant", state:"Texas", region:"North TX", type:"Private", sites:103, hookup:"Full hookups, covered and premium sites", phone:"(817) 550-2202", web:"midcitiesrvpark.com", tags:["Long-term stays","Covered sites","Dog park","Fiber internet"] },
  { name:"Yellow Rose RV Resort", address:"14445 White Settlement Rd, Fort Worth, TX 76108", year:"", city:"Fort Worth", county:"Parker", state:"Texas", region:"North TX", type:"Private", sites:147, hookup:"Full hookups, extra-wide back-in sites", phone:"(817) 229-8665", web:"yellowroservresort.com", tags:["21+ adult park","Pool","Dog parks","Big rig friendly"] },
  { name:"Highland Hideaway RV Resort", address:"1008 Highland Rd, Cleburne, TX 76033", year:"", city:"Cleburne", county:"Johnson", state:"Texas", region:"North TX", type:"Private", sites:108, hookup:"Full hookups, big rig friendly", phone:"(682) 916-3387", web:"highlandhideawayrvresort.com", tags:["Pool","Fitness center","Near downtown Cleburne"] },
  { name:"Northlake Village RV Park", address:"13001 Cleveland Gibbs Rd, Roanoke, TX 76262", year:"", city:"Roanoke", county:"Denton", state:"Texas", region:"North TX", type:"Private", sites:177, hookup:"Full hookups", phone:"(817) 430-3303", web:"northlakevillagerv.com", tags:["Near Texas Motor Speedway","DFW area","Long-term stays"] },
  { name:"Big Bend Station RV Park", address:"53623 TX-118, Terlingua, TX 79852", year:"", city:"Terlingua", county:"Brewster", state:"Texas", region:"Big Bend TX", type:"Private", sites:131, hookup:"Full hookups", phone:"(844) 637-0883", web:"bigbendstation.com", tags:["Near Big Bend National Park","Inn & RV combo","Restaurant on-site"] },
  { name:"Ransom Road RV Park", address:"240 Ransom Road, Aransas Pass, TX 78336", year:"", city:"Aransas Pass", county:"San Patricio", state:"Texas", region:"Coastal Bend TX", type:"Private", sites:128, hookup:"Full hookups", phone:"(361) 758-2715", web:"ransomroadrvparkinc.com", tags:["Intracoastal Waterway area","Gulf Coast fishing"] },
  { name:"Seven Oaks Resort", address:"801 South Inspiration Road, Mission, TX 78572", year:"", city:"Mission", county:"Hidalgo", state:"Texas", region:"Rio Grande Valley TX", type:"Private", sites:232, hookup:"Full hookups", phone:"(956) 581-0068", web:"sevenoaksresort.com", tags:["55+ resort","Pool & spa","Winter Texan destination"] },
  { name:"Paradise South RV Resort", address:"9099 N Mile 2 West Rd, Mercedes, TX 78570", year:"", city:"Mercedes", county:"Hidalgo", state:"Texas", region:"Rio Grande Valley TX", type:"Private", sites:493, hookup:"Full hookups", phone:"(956) 565-2044", web:"thousandtrails.com", tags:["55+ resort","Encore/Thousand Trails network","Winter Texan destination"] },

  // ──────────────────────────────────────────────────────────
  //  ADD YOUR NEXT STATE HERE
  //  Example template (copy and fill in):
  // ──────────────────────────────────────────────────────────
  //
  // { name:"Park Name",
  //   address:"123 Main St, City, ST 12345",
  //   city:"City", county:"County", state:"Georgia",
  //   region:"North GA",
  //   type:"Private",
  //   sites:45,
  //   hookup:"Full hookups, 30/50A",
  //   phone:"(555) 123-4567",
  //   web:"parkwebsite.com",         // leave "" if no website
  //   tags:["Lake","Fishing","Quiet"]
  // },

];
